"""
Xero ERP Integration

All Xero-specific API calls: journal entries, bills, vendors, credits,
settlements, attachments, and token refresh.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import httpx
from clearledgr.core.http_client import get_http_client

from clearledgr.core.money import money_to_float
from clearledgr.integrations.erp_sanitization import (
    _build_xero_vendor_lookup_where,
    _escape_query_literal,
    _sanitize_xero_where_operand,
)

logger = logging.getLogger(__name__)

_ERP_TIMEOUT = 30


def _xero_headers(
    connection,
    *,
    idempotency_key: Optional[str] = None,
) -> Dict[str, str]:
    headers = {
        "Authorization": f"Bearer {connection.access_token}",
        "Content-Type": "application/json",
        "xero-tenant-id": str(connection.tenant_id or ""),
    }
    if idempotency_key:
        headers["Idempotency-Key"] = str(idempotency_key)[:128]
    return headers


def _extract_xero_validation_message(payload: Optional[Dict[str, Any]]) -> Optional[str]:
    if not isinstance(payload, dict):
        return None
    message = str(payload.get("Message") or "").strip()
    if message:
        return message
    for key in ("Allocations", "Payments", "CreditNotes"):
        rows = payload.get(key)
        if not isinstance(rows, list):
            continue
        for row in rows:
            if not isinstance(row, dict):
                continue
            errors = row.get("ValidationErrors")
            if isinstance(errors, list) and errors:
                for err in errors:
                    if isinstance(err, dict):
                        detail = str(err.get("Message") or "").strip()
                        if detail:
                            return detail
    return None


# ==================== Journal Entry ====================

async def post_to_xero(
    connection,
    entry: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Post journal entry to Xero.

    Uses Xero API:
    https://developer.xero.com/documentation/api/accounting/manualjournals
    """
    if not connection.access_token or not connection.tenant_id:
        return {"status": "error", "erp": "xero", "reason": "Xero not properly configured"}

    # Build Xero manual journal format
    xero_journal = {
        "Date": entry.get("date", datetime.now(timezone.utc).strftime("%Y-%m-%d")),
        "Narration": entry.get("description", "Auto-generated by Clearledgr"),
        "JournalLines": [],
    }

    for line in entry.get("lines", []):
        xero_line = {
            "LineAmount": line.get("debit", 0) if line.get("debit", 0) > 0 else -line.get("credit", 0),
            "AccountCode": line.get("account", "200"),  # Xero uses account codes
            "Description": line.get("account_name", ""),
        }
        xero_journal["JournalLines"].append(xero_line)

    # Make API call
    url = "https://api.xero.com/api.xro/2.0/ManualJournals"

    try:
        client = get_http_client()
        response = await client.post(
            url,
            json={"ManualJournals": [xero_journal]},
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "Content-Type": "application/json",
                "xero-tenant-id": connection.tenant_id,
            },
            timeout=30,
        )

        if response.status_code == 401:
            logger.warning("Xero token expired, needs refresh")
            return {"status": "error", "erp": "xero", "reason": "Token expired", "needs_reauth": True}

        response.raise_for_status()
        result = response.json()

        journals = result.get("ManualJournals", [])
        if journals:
            journal_id = journals[0].get("ManualJournalID")
            logger.info(f"Posted to Xero: {journal_id}")
            return {
                "status": "success",
                "erp": "xero",
                "entry_id": journal_id,
            }

        return {"status": "error", "erp": "xero", "reason": "No journal returned"}

    except httpx.HTTPStatusError as e:
        logger.error("Xero API error: %s", e.response.status_code)
        return {"status": "error", "erp": "xero", "reason": f"Xero API {e.response.status_code}"}
    except Exception as e:
        logger.error("Xero error: %s", type(e).__name__)
        return {"status": "error", "erp": "xero", "reason": "posting_failed"}


# ==================== Token Refresh ====================

async def refresh_xero_token(connection) -> Optional[str]:
    """Refresh Xero OAuth token."""
    if not connection.refresh_token or not connection.client_id or not connection.client_secret:
        return None

    try:
        client = get_http_client()
        response = await client.post(
            "https://identity.xero.com/connect/token",
            data={
                "grant_type": "refresh_token",
                "refresh_token": connection.refresh_token,
            },
            auth=(connection.client_id, connection.client_secret),
        )
        response.raise_for_status()
        tokens = response.json()

        connection.access_token = tokens.get("access_token")
        connection.refresh_token = tokens.get("refresh_token")

        return connection.access_token
    except Exception as e:
        logger.error("Failed to refresh Xero token: %s", type(e).__name__)
        return None


# ==================== Bill Posting ====================

async def post_bill_to_xero(
    connection,
    bill,
    gl_map: Optional[Dict[str, str]] = None,
    field_mappings: Optional[Dict[str, str]] = None,
    custom_fields: Optional[Dict[str, str]] = None,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Post vendor bill to Xero.

    API: https://developer.xero.com/documentation/api/accounting/invoices
    Type: ACCPAY (Accounts Payable / Bill)

    ``field_mappings`` (Module 5) carries Xero tracking-category
    names (the customer's "Region", "Cost Centre", etc). Each line
    item gets ``Tracking`` entries set from the configured names so
    Xero's reports group on customer-defined dimensions. Workflow
    custom fields (``custom_fields``) appear on each line as
    ``Description`` suffixes — Xero has no per-bill custom-fields API.

    ``idempotency_key`` is forwarded to Xero as the ``Idempotency-Key``
    header (capped at 128 chars per Xero's spec) via ``_xero_headers``.
    Caller should pass a stable key derived from the AP item id so a
    transient timeout + retry doesn't create a duplicate ACCPAY
    invoice in the customer's Xero org.
    """
    from clearledgr.integrations.erp_router import get_account_code

    if not connection.access_token or not connection.tenant_id:
        return {"status": "error", "erp": "xero", "reason": "Xero not properly configured"}

    expense_account = get_account_code("xero", "expenses", gl_map)

    # Build Xero Invoice (ACCPAY type = Bill)
    xero_bill = {
        "Type": "ACCPAY",  # Accounts Payable = Bill
        "Contact": {"ContactID": bill.vendor_id, "Name": bill.vendor_name},
        "Date": bill.invoice_date or datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "DueDate": bill.due_date,
        "InvoiceNumber": bill.invoice_number,
        "Reference": bill.po_number,
        "Status": "AUTHORISED",  # Ready for payment
        "LineItems": [],
    }

    # Currency — post in the invoice's native currency. Xero requires
    # the currency to be set up on the organisation; if it isn't, the
    # API returns a clear "CurrencyCode not found" error the caller can
    # surface to the user.
    bill_currency = str(getattr(bill, "currency", "") or "").strip().upper()
    if bill_currency and len(bill_currency) == 3:
        xero_bill["CurrencyCode"] = bill_currency

    # Add line items.  Money boundary: quantize every amount before
    # serialising to the Xero payload so the wire value matches what
    # we stored internally in Decimal.
    # Tax-code propagation: Clearledgr vat_code -> Xero TaxType per
    # line. Operators map their tenant's TaxType ids via gl_map (e.g.
    # gl_map["tax_code_T1"] = "INPUT2" for a UK-VAT-registered Xero
    # tenant). Defaults below cover the standard Xero TaxType
    # namespace used for Bills (purchase side).
    bill_vat_code = str(getattr(bill, "vat_code", "") or "").upper()

    def _resolve_xero_tax_type(code: str) -> Optional[str]:
        if not code:
            return None
        if gl_map and gl_map.get(f"tax_code_{code}"):
            return str(gl_map[f"tax_code_{code}"])
        return _DEFAULT_XERO_TAXTYPE_MAP.get(code)

    if bill.line_items:
        for item in bill.line_items:
            line_vat = str(item.get("vat_code") or bill_vat_code or "").upper()
            tax_type = (
                item.get("tax_type")
                or _resolve_xero_tax_type(line_vat)
                or "NONE"
            )
            xero_line = {
                "Description": item.get("description", ""),
                "Quantity": item.get("quantity", 1),
                "UnitAmount": money_to_float(item.get("unit_amount", item.get("amount", 0))),
                "AccountCode": item.get("account_code", expense_account),
                "TaxType": tax_type,
            }
            # Module 5 Pass C — carry tracking_1/tracking_2 forward
            # from upstream line_items. The finalization step below
            # converts them to Xero's Tracking[] format using the
            # configured tracking-category names.
            if item.get("tracking_1") is not None:
                xero_line["tracking_1"] = item["tracking_1"]
            if item.get("tracking_2") is not None:
                xero_line["tracking_2"] = item["tracking_2"]
            xero_bill["LineItems"].append(xero_line)
    else:
        single_tax_type = _resolve_xero_tax_type(bill_vat_code) or "NONE"
        xero_bill["LineItems"].append({
            "Description": bill.description or f"Invoice {bill.invoice_number}",
            "Quantity": 1,
            "UnitAmount": money_to_float(bill.amount),
            "AccountCode": expense_account,
            "TaxType": single_tax_type,
        })

    # Apply tax to line items if tax_amount provided AND no explicit
    # vat_code on the bill (since the per-line TaxType above already
    # carries the right code). Honor the legacy "OUTPUT" default only
    # when no Clearledgr-side vat_code was set.
    if (
        getattr(bill, "tax_amount", None)
        and bill.tax_amount > 0
        and not bill_vat_code
    ):
        for li in xero_bill["LineItems"]:
            if li.get("TaxType") in (None, "", "NONE"):
                li["TaxType"] = "OUTPUT"  # Standard tax (legacy default)
        xero_bill["TotalTax"] = money_to_float(bill.tax_amount)

    # Apply discount as negative line
    if getattr(bill, "discount_amount", None) and bill.discount_amount > 0:
        xero_bill["LineItems"].append({
            "Description": f"Discount ({bill.discount_terms or 'early payment'})",
            "Quantity": 1,
            "UnitAmount": money_to_float(-bill.discount_amount),
            "AccountCode": expense_account,
            "TaxType": "NONE",
        })

    # Module 5 Pass C — Xero tracking categories per line. Operator
    # configures the Xero category names via the field-mapping form
    # (catalog keys ``tracking_category_1_field`` /
    # ``tracking_category_2_field``); the per-line tracking value
    # itself comes from the line's ``tracking_1`` / ``tracking_2``
    # entries when the upstream pipeline supplies them. We only emit
    # Tracking[] entries for lines that carry both pieces (name +
    # option) — empty configurations are silent no-ops.
    fm = field_mappings or {}
    track_1_name = (fm.get("tracking_category_1_field") or "").strip()
    track_2_name = (fm.get("tracking_category_2_field") or "").strip()
    if track_1_name or track_2_name:
        for li in xero_bill["LineItems"]:
            tracking = []
            if track_1_name and li.get("tracking_1"):
                tracking.append({
                    "Name": track_1_name,
                    "Option": str(li["tracking_1"]),
                })
            if track_2_name and li.get("tracking_2"):
                tracking.append({
                    "Name": track_2_name,
                    "Option": str(li["tracking_2"]),
                })
            if tracking:
                li["Tracking"] = tracking
            # Strip the upstream tracking_* keys regardless so they
            # don't leak into the Xero payload (Xero rejects unknown
            # keys at the LineItem level).
            li.pop("tracking_1", None)
            li.pop("tracking_2", None)

    # Module 5 Pass C — workflow custom fields. Xero has no first-class
    # custom-field API on Invoices; the operational compromise is to
    # append the workflow markers to the Reference field, which is
    # 255 chars and surfaces in the Xero UI alongside the bill. Format
    # is "<vendor po> | clearledgr:<state>:<box_id>" so the existing
    # po reference (set above) is preserved.
    if custom_fields:
        marker_parts = []
        for erp_field_id, value in custom_fields.items():
            if erp_field_id and value is not None:
                marker_parts.append(f"{erp_field_id}={value}")
        if marker_parts:
            existing_ref = str(xero_bill.get("Reference") or "").strip()
            marker = " | clearledgr:" + ";".join(marker_parts)
            new_ref = (existing_ref + marker) if existing_ref else marker.lstrip(" | ")
            # Cap at Xero's 255-char Reference limit so we never bounce
            # the whole bill on a payload-size validation error.
            xero_bill["Reference"] = new_ref[:255]

    url = "https://api.xero.com/api.xro/2.0/Invoices"

    try:
        client = get_http_client()
        response = await client.post(
            url,
            json={"Invoices": [xero_bill]},
            headers=_xero_headers(connection, idempotency_key=idempotency_key),
            timeout=30,
        )

        if response.status_code == 401:
            return {"status": "error", "erp": "xero", "reason": "Token expired", "needs_reauth": True}

        response.raise_for_status()
        result = response.json()

        invoices = result.get("Invoices", [])
        if invoices:
            inv = invoices[0]
            invoice_id = inv.get("InvoiceID")
            logger.info("Posted Bill to Xero: %s", invoice_id)

            # Wave 1 / A2 — Xero genuinely has a separate Journal
            # entity from the Invoice. The Journal record has a
            # ``JournalID`` that auditors trace independently. Fetch
            # it via /api.xro/2.0/Journals?invoiceID=<id> and persist
            # alongside the InvoiceID.
            #
            # Best-effort: a follow-up GET failure does not roll back
            # the post — the InvoiceID is still durable, and the
            # background reconciliation pass (Wave 5 work) will fill
            # in any missing JournalIDs from the Journals stream.
            journal_id = None
            try:
                if invoice_id:
                    journal_resp = await client.get(
                        "https://api.xero.com/api.xro/2.0/Journals",
                        params={"invoiceID": invoice_id},
                        headers={
                            "Authorization": f"Bearer {connection.access_token}",
                            "Xero-tenant-id": connection.tenant_id,
                            "Accept": "application/json",
                        },
                        timeout=15,
                    )
                    if journal_resp.status_code == 200:
                        journals = (journal_resp.json() or {}).get("Journals") or []
                        if journals:
                            journal_id = journals[0].get("JournalID")
            except Exception as exc:
                # Soft fail — the audit chain has the InvoiceID; JE
                # follow-up reconciliation will retry.
                logger.warning(
                    "[xero] JournalID fetch failed for invoice %s: %s",
                    invoice_id, exc,
                )

            return {
                "status": "success",
                "erp": "xero",
                "bill_id": invoice_id,
                "invoice_number": inv.get("InvoiceNumber"),
                "erp_journal_entry_id": (
                    str(journal_id) if journal_id else None
                ),
            }

        return {"status": "error", "erp": "xero", "reason": "no_invoice_returned"}

    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        # Parse Xero error response for actionable details
        erp_error_detail = ""
        erp_error_code = ""
        try:
            error_body = e.response.json()
            erp_error_code = str(error_body.get("ErrorNumber") or "")
            # Xero nests validation errors inside Elements[].ValidationErrors[]
            elements = error_body.get("Elements") or []
            validation_msgs = []
            for elem in elements:
                for verr in (elem.get("ValidationErrors") or []):
                    msg = verr.get("Message") or ""
                    if msg:
                        validation_msgs.append(msg)
            if validation_msgs:
                erp_error_detail = "; ".join(validation_msgs)
            else:
                erp_error_detail = error_body.get("Message") or ""
        except Exception:
            erp_error_detail = e.response.text[:200] if hasattr(e.response, "text") else ""

        detail_lower = erp_error_detail.lower()
        reason = f"http_{status_code}"
        if status_code == 404:
            reason = "erp_configuration_stale"
            logger.error(
                "Xero 404 — likely tenant_id mismatch (tenant_id=%s). "
                "Verify the organisation is accessible with current credentials.",
                connection.tenant_id,
            )
        elif "already exists" in detail_lower or "duplicate" in detail_lower:
            reason = "erp_duplicate_bill"
        elif "account code" in detail_lower and ("not valid" in detail_lower or "not found" in detail_lower):
            reason = "erp_gl_account_invalid"
        elif "contact" in detail_lower and "not found" in detail_lower:
            reason = "erp_vendor_not_found"

        logger.error(
            "Xero Bill API error: status=%d reason=%s detail=%s",
            status_code, reason, erp_error_detail[:200],
        )
        return {
            "status": "error",
            "erp": "xero",
            "reason": reason,
            "erp_error_detail": erp_error_detail,
            "erp_error_code": erp_error_code,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("Xero Bill error: %s", type(e).__name__)
        return {"status": "error", "erp": "xero", "reason": "bill_posting_failed"}


# ==================== Bill Reversal ====================


async def reverse_bill_from_xero(
    connection,
    erp_reference: str,
    *,
    reason: str,
) -> Dict[str, Any]:
    """Reverse a posted Xero bill by setting its Status to VOIDED.

    Xero supports voiding ACCPAY invoices directly as long as no payment
    has been applied. Since the override window (Phase 1.4) only allows
    reversals within a short interval after posting, the no-payment
    precondition should hold in practice. If it doesn't, Xero returns a
    validation error which we translate to ``payment_already_applied``.

    On success returns ``reversal_method="void"`` and ``reversal_ref`` equal
    to the original InvoiceID (Xero does not create a separate reversal
    document).
    """
    if not connection.access_token or not connection.tenant_id:
        return {
            "status": "error",
            "erp": "xero",
            "reason": "Xero not properly configured",
        }
    if not erp_reference:
        return {
            "status": "error",
            "erp": "xero",
            "reason": "missing_erp_reference",
        }

    url = f"https://api.xero.com/api.xro/2.0/Invoices/{erp_reference}"
    body = {
        "Invoices": [
            {
                "InvoiceID": erp_reference,
                "Status": "VOIDED",
            }
        ]
    }

    try:
        client = get_http_client()
        response = await client.post(
            url,
            json=body,
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "Content-Type": "application/json",
                "Accept": "application/json",
                "xero-tenant-id": connection.tenant_id,
            },
            timeout=30,
        )

        if response.status_code == 401:
            return {
                "status": "error",
                "erp": "xero",
                "reason": "Token expired",
                "needs_reauth": True,
            }

        if response.status_code == 404:
            return {
                "status": "already_reversed",
                "erp": "xero",
                "reference_id": erp_reference,
                "reversal_method": "void",
                "reversal_ref": erp_reference,
                "reason": "bill_not_found_in_erp",
            }

        response.raise_for_status()
        result = response.json() or {}
        invoices = result.get("Invoices") or []
        erp_status_raw = ""
        if invoices and isinstance(invoices[0], dict):
            erp_status_raw = str(invoices[0].get("Status") or "")

        if erp_status_raw.upper() != "VOIDED":
            logger.warning(
                "Xero reversal for %s returned status=%r (expected VOIDED)",
                erp_reference, erp_status_raw,
            )

        logger.info("Voided Xero Bill %s (reason=%s)", erp_reference, reason)
        return {
            "status": "success",
            "erp": "xero",
            "reference_id": erp_reference,
            "reversal_method": "void",
            "reversal_ref": erp_reference,
            "erp_status": erp_status_raw or "VOIDED",
        }

    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        erp_error_detail = ""
        erp_error_code = ""
        try:
            error_body = e.response.json() or {}
            erp_error_code = str(error_body.get("ErrorNumber") or "")
            elements = error_body.get("Elements") or []
            validation_msgs: List[str] = []
            for elem in elements:
                for verr in (elem.get("ValidationErrors") or []):
                    msg = verr.get("Message") or ""
                    if msg:
                        validation_msgs.append(msg)
            if validation_msgs:
                erp_error_detail = "; ".join(validation_msgs)
            else:
                erp_error_detail = error_body.get("Message") or ""
        except Exception:
            erp_error_detail = (
                e.response.text[:200] if hasattr(e.response, "text") else ""
            )

        detail_lower = erp_error_detail.lower()
        reason_code = f"http_{status_code}"

        if "payment" in detail_lower and (
            "allocated" in detail_lower
            or "applied" in detail_lower
            or "made against" in detail_lower
        ):
            reason_code = "payment_already_applied"
        elif "cannot" in detail_lower and "void" in detail_lower:
            reason_code = "cannot_void_invoice"
        elif "does not exist" in detail_lower or status_code == 404:
            return {
                "status": "already_reversed",
                "erp": "xero",
                "reference_id": erp_reference,
                "reversal_method": "void",
                "reversal_ref": erp_reference,
                "reason": "bill_not_found_in_erp",
            }

        logger.error(
            "Xero Bill reverse HTTP error: status=%d reason=%s detail=%s",
            status_code, reason_code, erp_error_detail[:200],
        )
        return {
            "status": "error",
            "erp": "xero",
            "reference_id": erp_reference,
            "reversal_method": "void",
            "reason": reason_code,
            "erp_error_detail": erp_error_detail,
            "erp_error_code": erp_error_code,
            "needs_reauth": status_code == 401,
        }
    except Exception as exc:
        logger.error(
            "Xero Bill reverse error: %s: %s", type(exc).__name__, exc
        )
        return {
            "status": "error",
            "erp": "xero",
            "reference_id": erp_reference,
            "reversal_method": "void",
            "reason": "bill_reversal_failed",
            "erp_error_detail": str(exc),
        }


# ==================== Credit Note Lookup & Application ====================

async def find_credit_note_xero(
    connection,
    credit_note_number: str,
) -> Optional[Dict[str, Any]]:
    """Find an AP credit note in Xero by document number."""
    if not connection.access_token or not connection.tenant_id:
        return None
    safe_number = _sanitize_xero_where_operand(credit_note_number)
    if not safe_number:
        return None
    literal = _escape_query_literal(safe_number)
    where_clause = f'Type=="ACCPAYCREDIT" AND CreditNoteNumber=="{literal}"'
    url = "https://api.xero.com/api.xro/2.0/CreditNotes"
    try:
        client = get_http_client()
        response = await client.get(
            url,
            params={"where": where_clause},
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "xero-tenant-id": connection.tenant_id,
            },
            timeout=30,
        )
        response.raise_for_status()
        credit_notes = response.json().get("CreditNotes", [])
        if credit_notes:
            note = credit_notes[0]
            return {
                "credit_note_id": note.get("CreditNoteID"),
                "credit_note_number": note.get("CreditNoteNumber"),
                "remaining_credit": note.get("RemainingCredit"),
                "status": note.get("Status"),
                "currency": note.get("CurrencyCode"),
                "erp": "xero",
            }
    except Exception as e:
        logger.error("Xero credit note lookup error: %s", e)
    return None


async def apply_credit_note_to_xero(
    connection,
    application,
    *,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """Allocate an existing Xero AP credit note against a posted bill."""
    if not connection.access_token or not connection.tenant_id:
        return {"status": "error", "erp": "xero", "reason": "Xero not properly configured"}

    missing_fields = []
    if not str(application.target_erp_reference or "").strip():
        missing_fields.append("target_erp_reference")
    if not str(application.credit_note_number or "").strip():
        missing_fields.append("credit_note_number")
    if float(application.amount or 0.0) <= 0:
        missing_fields.append("amount")
    if missing_fields:
        return {
            "status": "error",
            "erp": "xero",
            "reason": "xero_credit_application_validation_failed",
            "missing_fields": missing_fields,
        }

    credit_note = await find_credit_note_xero(connection, str(application.credit_note_number or ""))
    if not credit_note or not credit_note.get("credit_note_id"):
        return {
            "status": "error",
            "erp": "xero",
            "reason": "credit_note_not_found",
            "credit_note_number": application.credit_note_number,
        }

    remaining_credit = credit_note.get("remaining_credit")
    try:
        if remaining_credit is not None and round(float(application.amount or 0.0), 2) > round(float(remaining_credit), 2):
            return {
                "status": "error",
                "erp": "xero",
                "reason": "credit_amount_exceeds_remaining_credit",
                "credit_note_number": application.credit_note_number,
                "remaining_credit": round(float(remaining_credit), 2),
            }
    except (TypeError, ValueError):
        pass

    allocation_request = {
        "Allocations": [
            {
                "Invoice": {"InvoiceID": str(application.target_erp_reference).strip()},
                "Amount": round(float(application.amount or 0.0), 2),
                "Date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            }
        ]
    }
    url = f"https://api.xero.com/api.xro/2.0/CreditNotes/{credit_note['credit_note_id']}/Allocations"

    try:
        client = get_http_client()
        response = await client.put(
            url,
            params={"summarizeErrors": "true"},
            json=allocation_request,
            headers=_xero_headers(connection, idempotency_key=idempotency_key),
            timeout=30,
        )
        if response.status_code == 401:
            return {"status": "error", "erp": "xero", "reason": "Token expired", "needs_reauth": True}

        response.raise_for_status()
        payload = response.json()
        validation_message = _extract_xero_validation_message(payload)
        if validation_message:
            return {
                "status": "error",
                "erp": "xero",
                "reason": validation_message,
                "credit_note_number": application.credit_note_number,
            }

        allocations = payload.get("Allocations", [])
        if allocations:
            allocation = allocations[0]
            application_reference = (
                allocation.get("AllocationID")
                or f"{credit_note['credit_note_id']}:{str(application.target_erp_reference).strip()}"
            )
            return {
                "status": "success",
                "erp": "xero",
                "erp_reference": application_reference,
                "target_erp_reference": str(application.target_erp_reference).strip(),
                "credit_note_reference": credit_note.get("credit_note_id"),
                "credit_note_number": credit_note.get("credit_note_number"),
                "amount": allocation.get("Amount"),
            }

        return {"status": "error", "erp": "xero", "reason": "no_allocation_returned"}
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("Xero credit allocation HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            payload = e.response.json()
        except Exception:
            payload = None
        validation_message = _extract_xero_validation_message(payload)
        if validation_message:
            reason = validation_message
        return {
            "status": "error",
            "erp": "xero",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("Xero credit allocation error: %s", type(e).__name__)
        return {"status": "error", "erp": "xero", "reason": "credit_application_failed"}


# ==================== Settlement ====================

async def apply_settlement_to_xero(
    connection,
    application,
    *,
    gl_map: Optional[Dict[str, str]] = None,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """Create a Xero bill payment against a posted payable invoice."""
    from clearledgr.integrations.erp_router import get_account_code

    if not connection.access_token or not connection.tenant_id:
        return {"status": "error", "erp": "xero", "reason": "Xero not properly configured"}

    source_document_type = str(application.source_document_type or "").strip().lower()
    if source_document_type == "refund":
        return {
            "status": "error",
            "erp": "xero",
            "reason": "refund_settlement_api_not_available_for_connector",
        }

    missing_fields = []
    if not str(application.target_erp_reference or "").strip():
        missing_fields.append("target_erp_reference")
    if float(application.amount or 0.0) <= 0:
        missing_fields.append("amount")
    if missing_fields:
        return {
            "status": "error",
            "erp": "xero",
            "reason": "xero_settlement_validation_failed",
            "missing_fields": missing_fields,
        }

    payment_request = {
        "Payments": [
            {
                "Invoice": {"InvoiceID": str(application.target_erp_reference).strip()},
                "Account": {"Code": get_account_code("xero", "cash", gl_map)},
                "Date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                "Amount": round(float(application.amount or 0.0), 2),
            }
        ]
    }
    payment = payment_request["Payments"][0]
    if application.source_reference:
        payment["Reference"] = str(application.source_reference).strip()[:255]

    url = "https://api.xero.com/api.xro/2.0/Payments"
    try:
        client = get_http_client()
        response = await client.put(
            url,
            params={"summarizeErrors": "true"},
            json=payment_request,
            headers=_xero_headers(connection, idempotency_key=idempotency_key),
            timeout=30,
        )
        if response.status_code == 401:
            return {"status": "error", "erp": "xero", "reason": "Token expired", "needs_reauth": True}

        response.raise_for_status()
        payload = response.json()
        validation_message = _extract_xero_validation_message(payload)
        if validation_message:
            return {
                "status": "error",
                "erp": "xero",
                "reason": validation_message,
                "source_reference": application.source_reference,
            }

        payments = payload.get("Payments", [])
        if payments:
            payment_result = payments[0]
            return {
                "status": "success",
                "erp": "xero",
                "erp_reference": payment_result.get("PaymentID"),
                "payment_id": payment_result.get("PaymentID"),
                "target_erp_reference": str(application.target_erp_reference).strip(),
                "amount": payment_result.get("Amount"),
                "source_reference": payment_result.get("Reference") or application.source_reference,
            }

        return {"status": "error", "erp": "xero", "reason": "no_payment_returned"}
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("Xero settlement payment HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            payload = e.response.json()
        except Exception:
            payload = None
        validation_message = _extract_xero_validation_message(payload)
        if validation_message:
            reason = validation_message
        return {
            "status": "error",
            "erp": "xero",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("Xero settlement payment error: %s", type(e).__name__)
        return {"status": "error", "erp": "xero", "reason": "settlement_application_failed"}


# ==================== Vendor Management ====================

async def create_vendor_xero(
    connection,
    vendor,
) -> Dict[str, Any]:
    """Create vendor (Contact) in Xero."""
    if not connection.access_token or not connection.tenant_id:
        return {"status": "error", "erp": "xero", "reason": "Xero not configured"}

    xero_contact = {
        "Name": vendor.name,
        "IsSupplier": True,
        "ContactStatus": "ACTIVE",
    }

    if vendor.email:
        xero_contact["EmailAddress"] = vendor.email
    if vendor.phone:
        xero_contact["Phones"] = [{"PhoneType": "DEFAULT", "PhoneNumber": vendor.phone}]
    if vendor.tax_id:
        xero_contact["TaxNumber"] = vendor.tax_id
    if vendor.payment_terms:
        # Map to Xero payment terms
        days = int(''.join(filter(str.isdigit, vendor.payment_terms)) or "30")
        xero_contact["PaymentTerms"] = {"Bills": {"Day": days, "Type": "DAYSAFTERBILLDATE"}}

    url = "https://api.xero.com/api.xro/2.0/Contacts"

    try:
        client = get_http_client()
        response = await client.post(
            url,
            json={"Contacts": [xero_contact]},
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "Content-Type": "application/json",
                "xero-tenant-id": connection.tenant_id,
            },
            timeout=30,
        )
        response.raise_for_status()
        result = response.json()

        contacts = result.get("Contacts", [])
        if contacts:
            c = contacts[0]
            return {
                "status": "success",
                "vendor_id": c.get("ContactID"),
                "name": c.get("Name"),
            }
        return {"status": "error", "erp": "xero", "reason": "No contact returned"}
    except Exception as e:
        logger.error("Xero vendor creation error: %s", type(e).__name__)
        return {"status": "error", "erp": "xero", "reason": "vendor_creation_failed"}


async def find_vendor_xero(
    connection,
    name: Optional[str] = None,
    email: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Find vendor in Xero."""
    if not connection.access_token or not connection.tenant_id:
        return None

    url = "https://api.xero.com/api.xro/2.0/Contacts"
    name_operand = _sanitize_xero_where_operand(name)
    params = {"where": _build_xero_vendor_lookup_where(name_operand=name_operand)}

    try:
        client = get_http_client()
        response = await client.get(
            url,
            params=params,
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "xero-tenant-id": connection.tenant_id,
            },
            timeout=30,
        )
        response.raise_for_status()
        result = response.json()

        contacts = result.get("Contacts", [])
        for c in contacts:
            if email and c.get("EmailAddress") != email:
                continue
            return {
                "vendor_id": c.get("ContactID"),
                "name": c.get("Name"),
                "email": c.get("EmailAddress"),
            }
    except Exception as e:
        logger.error(f"Xero vendor search error: {e}")

    return None


# ==================== Bill Finder ====================

async def find_bill_xero(
    connection,
    invoice_number: str,
) -> Optional[Dict[str, Any]]:
    """Check if a bill (accounts payable invoice) already exists in Xero."""
    if not connection.access_token or not connection.tenant_id:
        return None
    safe_number = _sanitize_xero_where_operand(invoice_number)
    if not safe_number:
        return None
    literal = _escape_query_literal(safe_number)
    where_clause = f'Type=="ACCPAY" AND InvoiceNumber=="{literal}"'
    url = "https://api.xero.com/api.xro/2.0/Invoices"
    try:
        client = get_http_client()
        response = await client.get(
            url,
            params={"where": where_clause},
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "xero-tenant-id": connection.tenant_id,
            },
            timeout=30,
        )
        response.raise_for_status()
        invoices = response.json().get("Invoices", [])
        if invoices:
            inv = invoices[0]
            return {
                "bill_id": inv.get("InvoiceID"),
                "doc_number": inv.get("InvoiceNumber"),
                "amount": inv.get("Total"),
                "erp": "xero",
            }
    except Exception as e:
        logger.error("Xero bill lookup error: %s", e)
    return None


# ==================== Attachment ====================

async def _attach_to_xero(
    connection, bill_id: str, file_bytes: bytes, filename: str,
) -> Optional[Dict[str, Any]]:
    """Upload attachment to a Xero ACCPAY Invoice."""
    creds = connection.credentials or {}
    access_token = creds.get("access_token", "")
    tenant_id = creds.get("tenant_id", "")
    if not access_token or not tenant_id:
        return None
    safe_name = _sanitize_xero_where_operand(filename) or "invoice.pdf"
    url = f"https://api.xero.com/api.xro/2.0/Invoices/{bill_id}/Attachments/{safe_name}"
    headers = {
        "Authorization": f"Bearer {access_token}",
        "xero-tenant-id": tenant_id,
        "Content-Type": "application/pdf",
    }
    client = get_http_client()
    resp = await client.put(url, headers=headers, content=file_bytes, timeout=30)
    resp.raise_for_status()
    return {"attached": True, "erp": "xero"}


# ==================== Payment Status Lookup ====================

async def get_payment_status_xero(
    connection,
    bill_id: str,
) -> Dict[str, Any]:
    """Read payment status for a Xero ACCPAY invoice. GET only — never executes payments.

    Checks the invoice Status (PAID) or AmountDue == 0 for full payment.
    AmountDue > 0 but < Total means partial payment.
    """
    if not connection.access_token or not connection.tenant_id:
        return {"paid": False, "error": "Xero not properly configured"}

    url = f"https://api.xero.com/api.xro/2.0/Invoices/{bill_id}"
    try:
        client = get_http_client()
        response = await client.get(
            url,
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "xero-tenant-id": str(connection.tenant_id or ""),
            },
            timeout=30,
        )
        if response.status_code == 401:
            return {"paid": False, "error": "token_expired", "needs_reauth": True}

        response.raise_for_status()
        invoices = response.json().get("Invoices", [])
        if not invoices:
            return {"paid": False, "reason": "not_found"}

        invoice = invoices[0]
        status = str(invoice.get("Status") or "").upper()
        total = float(invoice.get("Total") or 0)
        amount_due = float(invoice.get("AmountDue") or 0)
        amount_paid = float(invoice.get("AmountPaid") or 0)

        # Extract payment details from Payments array if available
        payments = invoice.get("Payments") or []
        payment_date = ""
        payment_reference = ""
        has_voided_payment = False
        if isinstance(payments, list) and payments:
            last_payment = payments[-1]
            if isinstance(last_payment, dict):
                payment_date = str(last_payment.get("Date") or "").strip()
                payment_reference = str(last_payment.get("PaymentID") or "").strip()
            # Check for DELETED or VOIDED payments
            for pmt in payments:
                if isinstance(pmt, dict):
                    pmt_status = str(pmt.get("Status") or "").upper()
                    if pmt_status in ("DELETED", "VOIDED"):
                        has_voided_payment = True

        # Check for credit note applications
        credit_notes = invoice.get("CreditNotes") or []
        has_credits = isinstance(credit_notes, list) and len(credit_notes) > 0

        if status == "PAID" or (amount_due <= 0 and total > 0):
            # Determine closure method
            closure_method = "payment"
            if has_credits and not payment_reference:
                closure_method = "credit_applied"
            elif not payment_reference and not has_credits:
                closure_method = "unknown_non_payment"

            result = {
                "paid": True,
                "payment_amount": round(amount_paid or total, 2),
                "payment_date": payment_date,
                "payment_method": "",
                "payment_reference": payment_reference,
                "partial": False,
                "remaining_balance": 0.0,
            }
            if closure_method != "payment":
                result["closure_method"] = closure_method
            return result
        elif amount_paid > 0 and amount_due > 0:
            return {
                "paid": False,
                "payment_amount": round(amount_paid, 2),
                "payment_date": payment_date,
                "payment_method": "",
                "payment_reference": payment_reference,
                "partial": True,
                "remaining_balance": round(amount_due, 2),
            }
        else:
            # Check for voided/deleted payments indicating a failed payment
            if has_voided_payment:
                return {
                    "paid": False,
                    "payment_failed": True,
                    "reason": "payment_voided_or_deleted",
                }
            return {"paid": False, "reason": "unpaid"}
    except httpx.HTTPStatusError as e:
        logger.error("Xero payment status HTTP error: status=%d", e.response.status_code)
        return {"paid": False, "error": f"http_{e.response.status_code}"}
    except Exception as e:
        logger.error("Xero payment status error: %s", type(e).__name__)
        return {"paid": False, "error": "payment_status_lookup_failed"}


# ==================== Chart of Accounts ====================

# Default Clearledgr vat_code -> Xero TaxType map (purchase side).
# Operators override per-tenant via settings_json[gl_account_map]
# [tax_code_T1] = "<region-specific Xero TaxType>". Standard Xero
# regions: GB uses "INPUT2" (Standard 20%), AU uses "INPUT" (GST),
# NZ uses "INPUT2" (15%). Defaults assume GB for the EU/UK launch.
_DEFAULT_XERO_TAXTYPE_MAP: Dict[str, str] = {
    "T1": "INPUT2",          # Standard rated input (20% UK)
    "T0": "ZERORATEDINPUT",  # Zero-rated input
    "T2": "EXEMPTINPUT",     # Exempt input
    "RC": "REVERSECHARGES",  # Reverse charge — applies to services
    "OO": "NONE",            # Out of scope
}


_XERO_ACCOUNT_TYPE_MAP = {
    "bank": "asset",
    "current": "asset",
    "currliab": "liability",
    "depreciatn": "expense",
    "directcosts": "expense",
    "equity": "equity",
    "expense": "expense",
    "fixed": "asset",
    "inventory": "asset",
    "liability": "liability",
    "noncurrent": "asset",
    "otherincome": "revenue",
    "overheads": "expense",
    "prepayment": "asset",
    "revenue": "revenue",
    "sales": "revenue",
    "termliab": "liability",
    "paygliability": "liability",
    "superannuationexpense": "expense",
    "superannuationliability": "liability",
    "wagesexpense": "expense",
}


async def get_chart_of_accounts_xero(connection) -> List[Dict[str, Any]]:
    """Fetch all accounts from Xero.

    Returns a normalized list of account dicts.  Returns ``[]`` on any error
    so the caller is never blocked.
    """
    if not connection.access_token or not connection.tenant_id:
        return []

    url = "https://api.xero.com/api.xro/2.0/Accounts"
    try:
        client = get_http_client()
        response = await client.get(
            url,
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "xero-tenant-id": str(connection.tenant_id or ""),
            },
            timeout=60,
        )

        if response.status_code == 401:
            logger.warning("Xero token expired during chart-of-accounts fetch")
            return []

        response.raise_for_status()
        result = response.json()

        accounts: List[Dict[str, Any]] = []
        for acc in result.get("Accounts", []):
            raw_type = str(acc.get("Type") or "").strip().lower()
            accounts.append({
                "id": str(acc.get("AccountID") or ""),
                "code": str(acc.get("Code") or ""),
                "name": str(acc.get("Name") or ""),
                "type": _XERO_ACCOUNT_TYPE_MAP.get(raw_type, raw_type),
                "sub_type": str(acc.get("Class") or ""),
                "active": str(acc.get("Status") or "").upper() == "ACTIVE",
                "currency": str(acc.get("CurrencyCode") or ""),
            })
        return accounts

    except Exception as e:
        logger.error("Failed to fetch Xero chart of accounts: %s", type(e).__name__)
        return []


# ==================== Vendor List ====================


async def list_all_vendors_xero(connection) -> List[Dict[str, Any]]:
    """Fetch all supplier contacts from Xero with pagination.

    Xero Contacts API uses ``page`` (1-indexed, 100 per page).
    Filters to ``IsSupplier==true`` to get vendors only.
    Returns a normalized list of vendor dicts.  Returns ``[]`` on any error.
    """
    if not connection.access_token or not connection.tenant_id:
        return []

    url = "https://api.xero.com/api.xro/2.0/Contacts"
    headers = {
        "Authorization": f"Bearer {connection.access_token}",
        "xero-tenant-id": str(connection.tenant_id or ""),
    }
    page = 1
    all_vendors: List[Dict[str, Any]] = []

    try:
        client = get_http_client()
        while True:
            response = await client.get(
                url,
                params={
                    "where": "IsSupplier==true",
                    "page": page,
                },
                headers=headers,
                timeout=60,
            )

            if response.status_code == 401:
                logger.warning("Xero token expired during vendor list fetch")
                break

            response.raise_for_status()
            result = response.json()

            contacts = result.get("Contacts", [])
            if not contacts:
                break

            for c in contacts:
                addrs = c.get("Addresses") or []
                addr_parts = []
                for a in addrs:
                    if a.get("AddressType") == "POBOX" or a.get("AddressType") == "STREET":
                        addr_parts = list(filter(None, [
                            a.get("AddressLine1"), a.get("City"),
                            a.get("Region"), a.get("PostalCode"),
                            a.get("Country"),
                        ]))
                        break

                phones = c.get("Phones") or []
                phone = ""
                for p in phones:
                    if p.get("PhoneNumber"):
                        phone = str(p["PhoneNumber"])
                        break

                all_vendors.append({
                    "vendor_id": str(c.get("ContactID") or ""),
                    "name": str(c.get("Name") or ""),
                    "email": str(c.get("EmailAddress") or ""),
                    "phone": phone,
                    "tax_id": str(c.get("TaxNumber") or ""),
                    "currency": str(c.get("DefaultCurrency") or ""),
                    "active": str(c.get("ContactStatus") or "").upper() == "ACTIVE",
                    "address": ", ".join(addr_parts),
                    "payment_terms": "",
                    "balance": float(c.get("Balances", {}).get("AccountsPayable", {}).get("Outstanding") or 0),
                })

            if len(contacts) < 100:
                break
            page += 1

        return all_vendors

    except Exception as e:
        logger.error("Failed to fetch Xero vendor list: %s", type(e).__name__)
        return all_vendors or []


async def list_all_purchase_orders_xero(connection) -> List[Dict[str, Any]]:
    """Fetch all Purchase Orders from Xero with pagination.

    Xero PurchaseOrders API: 100 per page via `page` parameter. We filter
    to statuses that are actually matchable (DRAFT/SUBMITTED/AUTHORISED/
    BILLED skipped; we want ones that haven't been fully billed yet).
    Returns dicts compatible with PurchaseOrderStore.save_purchase_order.
    """
    if not connection.access_token or not connection.tenant_id:
        return []

    url = "https://api.xero.com/api.xro/2.0/PurchaseOrders"
    headers = {
        "Authorization": f"Bearer {connection.access_token}",
        "xero-tenant-id": str(connection.tenant_id or ""),
    }
    page = 1
    all_pos: List[Dict[str, Any]] = []

    def _status_from_xero(po: Dict[str, Any]) -> str:
        """Map Xero PO Status to our POStatus values."""
        status = str(po.get("Status") or "").strip().upper()
        if status == "DELETED":
            return "cancelled"
        if status == "BILLED":
            return "fully_invoiced"
        # AUTHORISED / SUBMITTED / DRAFT all treated as "approved" for
        # matching purposes — we only match to POs that could plausibly
        # have an invoice raised against them.
        return "approved"

    try:
        client = get_http_client()
        while True:
            response = await client.get(
                url,
                params={"page": page},
                headers=headers,
                timeout=60,
            )
            if response.status_code == 401:
                logger.warning("Xero token expired during PO list fetch")
                break
            response.raise_for_status()
            result = response.json()
            pos = result.get("PurchaseOrders", [])
            if not pos:
                break
            for po in pos:
                contact = po.get("Contact") or {}
                lines = []
                for li in (po.get("LineItems") or []):
                    lines.append({
                        "line_id": str(li.get("LineItemID") or ""),
                        "item_number": str(li.get("ItemCode") or ""),
                        "description": str(li.get("Description") or ""),
                        "quantity": float(li.get("Quantity") or 0.0),
                        "unit_price": float(li.get("UnitAmount") or 0.0),
                        "gl_code": str(li.get("AccountCode") or ""),
                    })
                all_pos.append({
                    "po_id": f"xero-po-{po.get('PurchaseOrderID')}",
                    "po_number": str(po.get("PurchaseOrderNumber") or ""),
                    "vendor_id": str(contact.get("ContactID") or ""),
                    "vendor_name": str(contact.get("Name") or ""),
                    "order_date": str(po.get("Date") or "")[:10],
                    "expected_delivery": str(po.get("DeliveryDate") or "")[:10] or None,
                    "line_items": lines,
                    "subtotal": float(po.get("SubTotal") or 0.0),
                    "tax_amount": float(po.get("TotalTax") or 0.0),
                    "total_amount": float(po.get("Total") or 0.0),
                    "currency": str(po.get("CurrencyCode") or "") or None,
                    "status": _status_from_xero(po),
                    "requested_by": "xero_sync",
                    "erp_po_id": str(po.get("PurchaseOrderID") or ""),
                })
            if len(pos) < 100:
                break
            page += 1

        return all_pos

    except Exception as e:
        logger.error("Failed to fetch Xero PO list: %s", type(e).__name__)
        return all_pos or []
