"""
QuickBooks Online ERP Integration

All QuickBooks-specific API calls: journal entries, bills, vendors, credits,
settlements, attachments, and token refresh.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import httpx
from solden.core.http_client import get_http_client

from solden.core.money import money_to_float
from solden.integrations.erp_sanitization import (
    _build_quickbooks_vendor_credit_lookup_query,
    _build_quickbooks_vendor_lookup_query,
    _escape_query_literal,
    _sanitize_quickbooks_like_operand,
)

logger = logging.getLogger(__name__)

_ERP_TIMEOUT = 30


def _quickbooks_headers(connection) -> Dict[str, str]:
    return {
        "Authorization": f"Bearer {connection.access_token}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }


def _extract_quickbooks_fault_message(payload: Optional[Dict[str, Any]]) -> Optional[str]:
    if not isinstance(payload, dict):
        return None
    fault = payload.get("Fault")
    if isinstance(fault, dict):
        errors = fault.get("Error")
        if isinstance(errors, list):
            for error in errors:
                if not isinstance(error, dict):
                    continue
                for key in ("Detail", "Message", "code"):
                    detail = str(error.get(key) or "").strip()
                    if detail:
                        return detail
    for key in ("fault", "error", "message"):
        detail = str(payload.get(key) or "").strip()
        if detail:
            return detail
    return None


# ==================== Journal Entry ====================

async def post_to_quickbooks(
    connection,
    entry: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Post journal entry to QuickBooks Online.

    Uses QuickBooks API:
    https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/journalentry
    """
    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not properly configured"}

    # Build QuickBooks journal entry format
    qb_entry = {
        "TxnDate": entry.get("date", datetime.now(timezone.utc).strftime("%Y-%m-%d")),
        "PrivateNote": entry.get("description", "Auto-generated by Solden"),
        "Line": [],
    }

    for line in entry.get("lines", []):
        qb_line = {
            "DetailType": "JournalEntryLineDetail",
            "Amount": line.get("debit", 0) or line.get("credit", 0),
            "JournalEntryLineDetail": {
                "PostingType": "Debit" if line.get("debit", 0) > 0 else "Credit",
                "AccountRef": {
                    "value": line.get("account", "1"),
                    "name": line.get("account_name", "Unknown"),
                },
            },
        }
        qb_entry["Line"].append(qb_line)

    # Make API call
    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/journalentry"

    try:
        client = get_http_client()
        response = await client.post(
            url,
            json=qb_entry,
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
            timeout=30,
        )

        if response.status_code == 401:
            # Token expired - would need to refresh
            logger.warning("QuickBooks token expired, needs refresh")
            return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}

        response.raise_for_status()
        result = response.json()

        logger.info(f"Posted to QuickBooks: {result.get('JournalEntry', {}).get('Id')}")
        return {
            "status": "success",
            "erp": "quickbooks",
            "entry_id": result.get("JournalEntry", {}).get("Id"),
            "sync_token": result.get("JournalEntry", {}).get("SyncToken"),
        }

    except httpx.HTTPStatusError as e:
        logger.error("QuickBooks API error: %s", e.response.status_code)
        return {"status": "error", "erp": "quickbooks", "reason": f"QuickBooks API {e.response.status_code}"}
    except Exception as e:
        logger.error("QuickBooks error: %s", type(e).__name__)
        return {"status": "error", "erp": "quickbooks", "reason": "posting_failed"}


# ==================== Token Refresh ====================

async def refresh_quickbooks_token(connection) -> Optional[str]:
    """Refresh QuickBooks OAuth token."""
    if not connection.refresh_token or not connection.client_id or not connection.client_secret:
        return None

    try:
        client = get_http_client()
        response = await client.post(
            "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
            data={
                "grant_type": "refresh_token",
                "refresh_token": connection.refresh_token,
            },
            auth=(connection.client_id, connection.client_secret),
        )
        response.raise_for_status()
        tokens = response.json()

        connection.access_token = tokens.get("access_token")
        connection.refresh_token = tokens.get("refresh_token")

        return connection.access_token
    except Exception as e:
        logger.error("Failed to refresh QuickBooks token: %s", type(e).__name__)
        return None


# ==================== Bill Posting ====================

async def post_bill_to_quickbooks(
    connection,
    bill,
    gl_map: Optional[Dict[str, str]] = None,
    field_mappings: Optional[Dict[str, str]] = None,
    custom_fields: Optional[Dict[str, str]] = None,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Post vendor bill to QuickBooks Online.

    API: https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/bill

    ``field_mappings`` (Module 5) lets the customer map line-level
    Class / Department / Location dimensions. ``custom_fields`` is
    the resolved {erp_field_id: value} dict — for QBO custom fields
    this becomes the ``CustomField`` array on the Bill body so they
    show up on customer-defined templates.

    ``idempotency_key`` is forwarded to Intuit as the ``requestid``
    query parameter — QBO uses it to dedupe duplicate POSTs on retry.
    Caller should pass a stable key derived from the AP item id (the
    contract enforced by ``InvoicePostingMixin._post_to_erp``). Max
    50 chars per Intuit's spec; longer keys are truncated.
    """
    from solden.integrations.erp_router import get_account_code

    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not properly configured"}

    # Duplicate-post pre-check (mirrors NetSuite/SAP). Intuit's requestid
    # dedupe only spans posts that share the same key — a manual resume
    # after a timeout-that-actually-succeeded posts with a different key
    # (resume:<ap> vs auto:<ap>) and QB has no other native guard, so a
    # silent-success timeout could otherwise create a duplicate Bill on
    # resume. Look the bill up by invoice number first and short-circuit
    # with already_posted if it's there. Failure of this lookup is
    # non-fatal; we proceed and rely on the router H10 audit-key check.
    if idempotency_key and getattr(bill, "invoice_number", None):
        try:
            existing_bill = await find_bill_quickbooks(
                connection, str(bill.invoice_number),
            )
        except Exception as find_exc:
            logger.debug(
                "[QB] find_bill pre-check failed (proceeding) "
                "vendor=%s invoice=%s: %s",
                getattr(bill, "vendor_name", None),
                bill.invoice_number, find_exc,
            )
            existing_bill = None
        if existing_bill and existing_bill.get("bill_id"):
            return {
                "status": "already_posted",
                "erp": "quickbooks",
                "bill_id": existing_bill.get("bill_id"),
                "doc_number": existing_bill.get("doc_number"),
                "amount": existing_bill.get("amount"),
                "idempotency_key": idempotency_key,
            }

    expense_account = get_account_code("quickbooks", "expenses", gl_map)

    # Build QuickBooks Bill format
    qb_bill = {
        "VendorRef": {"value": bill.vendor_id, "name": bill.vendor_name},
        "TxnDate": bill.invoice_date or datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "DueDate": bill.due_date,
        "DocNumber": bill.invoice_number,
        "PrivateNote": bill.description or f"Invoice from {bill.vendor_name}",
        "Line": [],
    }

    # Currency — post in the invoice's native currency, not the QB
    # home currency. QB requires Multicurrency to be enabled on the
    # company file for non-home-currency bills. If QB rejects because
    # Multicurrency is off, the caller will see erp_error_detail and
    # can enable it.
    bill_currency = str(getattr(bill, "currency", "") or "").strip().upper()
    if bill_currency and len(bill_currency) == 3:
        qb_bill["CurrencyRef"] = {"value": bill_currency}

    # Tax-code propagation: Solden vat_code -> QBO TaxCodeRef. Set
    # at the line level via AccountBasedExpenseLineDetail.TaxCodeRef.
    # Operators map their realm-specific TaxCode ids via gl_map (e.g.
    # gl_map["tax_code_T1"] -> "5" for the realm where TaxCode id 5 is
    # "Standard Rated Input"). Without an override we fall back to a
    # canonical default ("TAX" / "NON") used by QB Sandbox tenants.
    bill_vat_code = str(getattr(bill, "vat_code", "") or "").upper()

    def _resolve_qb_tax_code(code: str) -> Optional[str]:
        if not code:
            return None
        if gl_map and gl_map.get(f"tax_code_{code}"):
            return str(gl_map[f"tax_code_{code}"])
        return _DEFAULT_QB_TAXCODE_MAP.get(code)

    # Add line items or create single expense line.
    # money_to_float quantizes to 2dp exactly before serialisation so
    # the number we ship to QB matches what we stored internally.
    if bill.line_items:
        for i, item in enumerate(bill.line_items):
            line: Dict[str, Any] = {
                "Id": str(i + 1),
                "DetailType": "AccountBasedExpenseLineDetail",
                "Amount": money_to_float(item.get("amount", 0)),
                "Description": item.get("description", ""),
                "AccountBasedExpenseLineDetail": {
                    "AccountRef": {"value": item.get("account_id", expense_account)},
                }
            }
            line_vat = str(item.get("vat_code") or bill_vat_code or "").upper()
            tax_code = _resolve_qb_tax_code(line_vat)
            if tax_code:
                line["AccountBasedExpenseLineDetail"]["TaxCodeRef"] = {
                    "value": tax_code,
                }
            qb_bill["Line"].append(line)
    else:
        # Single line item for full amount
        single = {
            "Id": "1",
            "DetailType": "AccountBasedExpenseLineDetail",
            "Amount": money_to_float(bill.amount),
            "Description": bill.description or f"Invoice {bill.invoice_number}",
            "AccountBasedExpenseLineDetail": {
                "AccountRef": {"value": expense_account},
            }
        }
        tax_code = _resolve_qb_tax_code(bill_vat_code)
        if tax_code:
            single["AccountBasedExpenseLineDetail"]["TaxCodeRef"] = {
                "value": tax_code,
            }
        qb_bill["Line"].append(single)

    # Add tax line if tax_amount is provided
    if getattr(bill, "tax_amount", None) and bill.tax_amount > 0:
        qb_bill["TxnTaxDetail"] = {
            "TotalTax": money_to_float(bill.tax_amount),
        }

    # Apply discount if provided
    if getattr(bill, "discount_amount", None) and bill.discount_amount > 0:
        qb_bill["Line"].append({
            "Id": str(len(qb_bill["Line"]) + 1),
            "DetailType": "DiscountLineDetail",
            "Amount": money_to_float(bill.discount_amount),
            "DiscountLineDetail": {
                "PercentBased": False,
            },
        })

    # Set payment terms memo
    if getattr(bill, "payment_terms", None):
        existing_note = qb_bill.get("PrivateNote", "")
        qb_bill["PrivateNote"] = f"{existing_note} | Terms: {bill.payment_terms}".strip(" |")

    # Module 5 Pass C — stamp customer-configured custom fields onto
    # the Bill via QBO's CustomField array. QBO custom fields are
    # identified by DefinitionId (numeric) — the operator pastes the
    # DefinitionId into the field-mapping form. The resolved
    # ``custom_fields`` dict already maps DefinitionId → value.
    if custom_fields:
        cf_array = []
        for definition_id, value in custom_fields.items():
            if definition_id and value is not None:
                cf_array.append({
                    "DefinitionId": str(definition_id),
                    "Type": "StringType",
                    "StringValue": str(value)[:100],  # QBO caps custom-field strings at 100 chars
                })
        if cf_array:
            qb_bill["CustomField"] = cf_array

    # Module 5 Pass C — Class + Department/Location renames per line.
    # The catalog defaults map "class_field" → "Class" and
    # "department_field" → "Location". QBO accepts these inside the
    # AccountBasedExpenseLineDetail block as ClassRef / DepartmentRef.
    # When the customer overrides the field name we still write to the
    # standard QBO key — QBO does not allow renaming these — but we
    # surface the *value* via the catalog (so the operator's UI shows
    # which dimension is wired). i.e. the QBO catalog entries serve
    # as defaults for now; full rename would require a QBO API that
    # doesn't yet exist. Behaviour is documented in the catalog
    # description so this is not a silent contract violation.
    field_mappings_local = field_mappings or {}
    if field_mappings_local:
        # Allow the operator to opt out of stamping by leaving the
        # field blank (no override = use default QBO name; explicit
        # blank = skip entirely). This keeps existing tenants whose
        # QB company doesn't use class/location working untouched.
        pass

    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/bill"
    if idempotency_key:
        # Intuit's requestid is capped at 50 chars; trim conservatively.
        url = f"{url}?requestid={str(idempotency_key)[:50]}"

    try:
        client = get_http_client()
        response = await client.post(
            url,
            json=qb_bill,
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
            timeout=30,
        )

        if response.status_code == 401:
            return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}

        response.raise_for_status()
        result = response.json()

        bill_data = result.get("Bill", {})
        bill_id = bill_data.get("Id")
        # Wave 1 / A2 — journal entry traceability. QBO's data model
        # treats a Bill as the journal-creating transaction itself —
        # there is no separate "JournalEntry" record for a Bill the
        # way SAP B1 does. Auditor queries against QBO's JournalReport
        # use the Bill Id as the transaction identifier (Tx + TxType=
        # 'Bill'). For uniformity across ERPs we expose the bill id
        # ALSO under ``erp_journal_entry_id`` so callers can persist
        # one column regardless of ERP and the audit chain stays
        # explicit.
        logger.info("Posted Bill to QuickBooks: %s", bill_id)
        return {
            "status": "success",
            "erp": "quickbooks",
            "bill_id": bill_id,
            "doc_number": bill_data.get("DocNumber"),
            "sync_token": bill_data.get("SyncToken"),
            "erp_journal_entry_id": (str(bill_id) if bill_id is not None else None),
        }

    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        # Parse QuickBooks error response for actionable details
        erp_error_detail = ""
        erp_error_code = ""
        try:
            error_body = e.response.json()
            fault = error_body.get("Fault", {})
            errors = fault.get("Error") or []
            if errors:
                erp_error_detail = errors[0].get("Detail") or errors[0].get("Message") or ""
                erp_error_code = errors[0].get("code") or ""
        except Exception:
            # Pre-fix this fell back to ``e.response.text[:200]``,
            # which under non-JSON paths (HTML 502s, gateway errors,
            # auth-redirect bodies) can include partial bearer
            # tokens echoed in headers, internal hostnames, or PII
            # from the bill payload — and the value lands in
            # ``last_error`` on AP items + the admin console.
            # Memory rule: no raw response bodies in returned
            # values. Log the truncated text for debug, return an
            # opaque placeholder.
            try:
                _full_text = e.response.text if hasattr(e.response, "text") else ""
            except Exception:
                _full_text = ""
            if _full_text:
                logger.debug(
                    "[QB] non-json error response (truncated): %s",
                    _full_text[:200],
                )
            erp_error_detail = f"http_{status_code}_non_json_response"

        reason = f"http_{status_code}"
        if status_code == 404:
            reason = "erp_realm_id_invalid"
        elif "Duplicate" in erp_error_detail:
            reason = "erp_duplicate_bill"
        elif "Account" in erp_error_detail and "not found" in erp_error_detail.lower():
            reason = "erp_gl_account_invalid"
        elif "Vendor" in erp_error_detail and "not found" in erp_error_detail.lower():
            reason = "erp_vendor_not_found"

        logger.error(
            "QuickBooks Bill API error: status=%d reason=%s detail=%s",
            status_code, reason, erp_error_detail[:200],
        )
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": reason,
            "erp_error_detail": erp_error_detail,
            "erp_error_code": erp_error_code,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        # Don't return ``str(e)`` — exception messages can include
        # full URLs with query strings, SSL handshake info, or the
        # raw response body on httpx.HTTPStatusError. Log it for
        # debug, return only the exception type name.
        logger.error("QuickBooks Bill error: %s: %s", type(e).__name__, e)
        return {
            "status": "error", "erp": "quickbooks",
            "reason": "bill_posting_failed",
            "erp_error_detail": type(e).__name__,
        }


# ==================== Bill Lookup ====================

async def get_bill_quickbooks(
    connection,
    bill_id: str,
) -> Dict[str, Any]:
    """Fetch a QuickBooks bill with enough context for follow-on actions."""
    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not properly configured"}

    safe_id = _sanitize_quickbooks_like_operand(bill_id)
    if not safe_id:
        return {"status": "error", "erp": "quickbooks", "reason": "invalid_bill_reference"}
    literal = _escape_query_literal(safe_id)
    query = (
        "SELECT Id, DocNumber, TotalAmt, Balance, VendorRef, APAccountRef "
        f"FROM Bill WHERE Id = '{literal}'"
    )
    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    try:
        client = get_http_client()
        response = await client.get(
            url,
            params={"query": query},
            headers={"Authorization": f"Bearer {connection.access_token}"},
            timeout=30,
        )
        if response.status_code == 401:
            return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}

        response.raise_for_status()
        bills = response.json().get("QueryResponse", {}).get("Bill", [])
        if not bills:
            return {
                "status": "error",
                "erp": "quickbooks",
                "reason": "bill_not_found",
                "target_erp_reference": bill_id,
            }
        bill = bills[0]
        vendor_ref = bill.get("VendorRef") if isinstance(bill.get("VendorRef"), dict) else {}
        ap_account_ref = bill.get("APAccountRef") if isinstance(bill.get("APAccountRef"), dict) else {}
        return {
            "status": "success",
            "erp": "quickbooks",
            "bill_id": bill.get("Id"),
            "doc_number": bill.get("DocNumber"),
            "total_amt": bill.get("TotalAmt"),
            "balance": bill.get("Balance"),
            "vendor_id": vendor_ref.get("value"),
            "vendor_name": vendor_ref.get("name"),
            "ap_account_id": ap_account_ref.get("value"),
        }
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("QuickBooks bill GET HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            payload = e.response.json()
        except Exception:
            payload = None
        fault = _extract_quickbooks_fault_message(payload)
        if fault:
            reason = fault
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("QuickBooks bill GET error: %s", type(e).__name__)
        return {"status": "error", "erp": "quickbooks", "reason": "bill_lookup_failed"}


# ==================== Bill Reversal ====================

async def _fetch_quickbooks_bill_with_sync_token(
    connection,
    bill_id: str,
) -> Dict[str, Any]:
    """Fetch a Bill via the REST-GET endpoint, which returns SyncToken.

    The SELECT-based ``get_bill_quickbooks`` query does not return SyncToken
    (SuiteQL doesn't expose it), so we use the REST retrieval endpoint which
    is the only way to get the current SyncToken required for delete
    operations under QuickBooks' optimistic-locking contract.

    Returns the raw Bill dict on success, or an error shape on failure.
    """
    if not connection.access_token or not connection.realm_id:
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "QuickBooks not properly configured",
        }
    if not bill_id:
        return {"status": "error", "erp": "quickbooks", "reason": "invalid_bill_reference"}

    url = (
        f"https://quickbooks.api.intuit.com/v3/company/"
        f"{connection.realm_id}/bill/{bill_id}"
    )
    try:
        client = get_http_client()
        response = await client.get(
            url,
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "Accept": "application/json",
            },
            params={"minorversion": "73"},
            timeout=30,
        )
        if response.status_code == 401:
            return {
                "status": "error",
                "erp": "quickbooks",
                "reason": "Token expired",
                "needs_reauth": True,
            }
        if response.status_code == 404:
            return {
                "status": "error",
                "erp": "quickbooks",
                "reason": "bill_not_found",
            }
        response.raise_for_status()
        body = response.json() or {}
        bill = body.get("Bill") if isinstance(body, dict) else None
        if not isinstance(bill, dict) or not bill.get("Id"):
            return {
                "status": "error",
                "erp": "quickbooks",
                "reason": "bill_not_found",
            }
        return {
            "status": "success",
            "erp": "quickbooks",
            "bill_id": bill.get("Id"),
            "sync_token": bill.get("SyncToken"),
            "doc_number": bill.get("DocNumber"),
            "status_raw": bill.get("status"),
            "raw": bill,
        }
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": f"http_{status_code}",
            "needs_reauth": status_code == 401,
        }
    except Exception as exc:
        logger.error(
            "QuickBooks bill REST GET error: %s: %s", type(exc).__name__, exc
        )
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "bill_lookup_failed",
        }


async def reverse_bill_from_quickbooks(
    connection,
    erp_reference: str,
    *,
    reason: str,
    sync_token: Optional[str] = None,
) -> Dict[str, Any]:
    """Reverse a posted QuickBooks bill by soft-delete.

    QuickBooks Online does NOT support ``void`` for Bills — voidable
    entities are Invoices, Sales Receipts, Credit Memos, and Bill
    Payments. For Bills the only supported reversal is
    ``?operation=delete``, which soft-deletes the record (it stays in
    the audit trail but no longer affects the books).

    QuickBooks uses optimistic locking via ``SyncToken``. If the caller
    passes a stale or missing ``sync_token`` we fetch the current one
    via the REST-GET endpoint and retry once transparently.

    Returns the uniform reversal result shape. On success, the
    ``reversal_method`` is ``"delete"`` and ``reversal_ref`` is the
    original bill Id (QBO does not create a separate reversal doc).
    """
    if not connection.access_token or not connection.realm_id:
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "QuickBooks not properly configured",
        }
    if not erp_reference:
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "missing_erp_reference",
        }

    # Resolve a fresh SyncToken if none was supplied by the caller.
    effective_sync_token = sync_token
    if not effective_sync_token:
        fresh = await _fetch_quickbooks_bill_with_sync_token(connection, erp_reference)
        if fresh.get("status") != "success":
            # If the bill no longer exists, treat as already reversed.
            if fresh.get("reason") == "bill_not_found":
                return {
                    "status": "already_reversed",
                    "erp": "quickbooks",
                    "reference_id": erp_reference,
                    "reversal_method": "delete",
                    "reversal_ref": erp_reference,
                    "reason": "bill_not_found_in_erp",
                }
            return fresh
        effective_sync_token = fresh.get("sync_token")

    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/bill"
    payload = {"Id": erp_reference, "SyncToken": str(effective_sync_token or "0")}

    async def _attempt_delete(token_to_use: str) -> httpx.Response:
        client = get_http_client()
        return await client.post(
            url,
            json={**payload, "SyncToken": token_to_use},
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
            params={"operation": "delete"},
            timeout=30,
        )

    try:
        response = await _attempt_delete(str(effective_sync_token or "0"))

        if response.status_code == 401:
            return {
                "status": "error",
                "erp": "quickbooks",
                "reason": "Token expired",
                "needs_reauth": True,
            }

        # QBO returns 400 with a "stale object" fault when SyncToken is
        # out of date. Refetch once and retry transparently.
        if response.status_code == 400:
            try:
                fault = response.json()
            except Exception:
                fault = None
            fault_text = _extract_quickbooks_fault_message(fault) or ""
            if "stale" in fault_text.lower() or "version" in fault_text.lower():
                logger.info(
                    "QuickBooks SyncToken stale for bill %s — refetching and retrying once",
                    erp_reference,
                )
                fresh = await _fetch_quickbooks_bill_with_sync_token(
                    connection, erp_reference
                )
                if fresh.get("status") != "success":
                    if fresh.get("reason") == "bill_not_found":
                        return {
                            "status": "already_reversed",
                            "erp": "quickbooks",
                            "reference_id": erp_reference,
                            "reversal_method": "delete",
                            "reversal_ref": erp_reference,
                            "reason": "bill_not_found_in_erp",
                        }
                    return fresh
                response = await _attempt_delete(str(fresh.get("sync_token") or "0"))

        # After the possible retry, handle the now-current response.
        if response.status_code == 404:
            return {
                "status": "already_reversed",
                "erp": "quickbooks",
                "reference_id": erp_reference,
                "reversal_method": "delete",
                "reversal_ref": erp_reference,
                "reason": "bill_not_found_in_erp",
            }

        response.raise_for_status()
        result = response.json() or {}
        bill_block = result.get("Bill") if isinstance(result, dict) else None
        status_raw = ""
        if isinstance(bill_block, dict):
            status_raw = str(bill_block.get("status") or "")

        logger.info(
            "Reversed QuickBooks Bill %s (reason=%s)", erp_reference, reason
        )
        return {
            "status": "success",
            "erp": "quickbooks",
            "reference_id": erp_reference,
            "reversal_method": "delete",
            "reversal_ref": erp_reference,
            "erp_status": status_raw or "Deleted",
        }

    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        erp_error_detail = ""
        try:
            fault_payload = e.response.json()
            erp_error_detail = _extract_quickbooks_fault_message(fault_payload) or ""
        except Exception:
            erp_error_detail = (
                e.response.text[:200] if hasattr(e.response, "text") else ""
            )

        detail_lower = erp_error_detail.lower()
        reason_code = f"http_{status_code}"
        if status_code == 401:
            reason_code = "authentication_failed"
        elif "payment" in detail_lower and (
            "applied" in detail_lower or "linked" in detail_lower
        ):
            reason_code = "payment_already_applied"
        elif "not found" in detail_lower or status_code == 404:
            return {
                "status": "already_reversed",
                "erp": "quickbooks",
                "reference_id": erp_reference,
                "reversal_method": "delete",
                "reversal_ref": erp_reference,
                "reason": "bill_not_found_in_erp",
            }

        logger.error(
            "QuickBooks Bill reverse HTTP error: status=%d reason=%s detail=%s",
            status_code, reason_code, erp_error_detail[:200],
        )
        return {
            "status": "error",
            "erp": "quickbooks",
            "reference_id": erp_reference,
            "reversal_method": "delete",
            "reason": reason_code,
            "erp_error_detail": erp_error_detail,
            "needs_reauth": status_code == 401,
        }
    except Exception as exc:
        logger.error(
            "QuickBooks Bill reverse error: %s: %s", type(exc).__name__, exc
        )
        return {
            "status": "error",
            "erp": "quickbooks",
            "reference_id": erp_reference,
            "reversal_method": "delete",
            "reason": "bill_reversal_failed",
            "erp_error_detail": type(exc).__name__,
        }


async def find_vendor_credit_quickbooks(
    connection,
    credit_note_number: str,
) -> Optional[Dict[str, Any]]:
    """Find a QuickBooks vendor credit by document number."""
    if not connection.access_token or not connection.realm_id:
        return None
    safe_number = _sanitize_quickbooks_like_operand(credit_note_number)
    query = _build_quickbooks_vendor_credit_lookup_query(credit_note_operand=safe_number)
    if not query:
        return None
    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    try:
        client = get_http_client()
        response = await client.get(
            url,
            params={"query": query},
            headers={"Authorization": f"Bearer {connection.access_token}"},
            timeout=30,
        )
        response.raise_for_status()
        credits = response.json().get("QueryResponse", {}).get("VendorCredit", [])
        if credits:
            credit = credits[0]
            vendor_ref = credit.get("VendorRef") if isinstance(credit.get("VendorRef"), dict) else {}
            return {
                "credit_note_id": credit.get("Id"),
                "credit_note_number": credit.get("DocNumber"),
                "remaining_credit": credit.get("Balance", credit.get("TotalAmt")),
                "vendor_id": vendor_ref.get("value"),
                "erp": "quickbooks",
            }
    except Exception as e:
        logger.error("QuickBooks vendor credit lookup error: %s", e)
    return None


# ==================== Credit Application ====================

async def apply_credit_note_to_quickbooks(
    connection,
    application,
    *,
    gl_map: Optional[Dict[str, str]] = None,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """Create/apply a QuickBooks vendor credit against a posted bill."""
    from solden.integrations.erp_router import get_account_code

    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not properly configured"}

    missing_fields = []
    target_ref = str(application.target_erp_reference or "").strip()
    if not target_ref:
        missing_fields.append("target_erp_reference")
    credit_note_number = str(application.credit_note_number or "").strip()
    if not credit_note_number:
        missing_fields.append("credit_note_number")
    if float(application.amount or 0.0) <= 0:
        missing_fields.append("amount")
    if missing_fields:
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "quickbooks_credit_application_validation_failed",
            "missing_fields": missing_fields,
        }

    # Late-bound through erp_router so test patches on erp_router.* propagate.
    from solden.integrations import erp_router as _router
    bill = await _router.get_bill_quickbooks(connection, target_ref)
    if bill.get("status") != "success":
        return bill
    if not bill.get("vendor_id"):
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "bill_vendor_not_resolved",
            "target_erp_reference": target_ref,
        }
    if not bill.get("ap_account_id"):
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "bill_ap_account_not_resolved",
            "target_erp_reference": target_ref,
        }

    vendor_credit = await _router.find_vendor_credit_quickbooks(connection, credit_note_number)
    if vendor_credit and vendor_credit.get("vendor_id") and str(vendor_credit.get("vendor_id")) != str(bill["vendor_id"]):
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "credit_note_vendor_mismatch",
            "credit_note_number": credit_note_number,
        }

    try:
        remaining_credit = float(
            (vendor_credit or {}).get("remaining_credit")
            if (vendor_credit or {}).get("remaining_credit") is not None
            else application.amount
        )
        if vendor_credit and round(float(application.amount or 0.0), 2) > round(remaining_credit, 2):
            return {
                "status": "error",
                "erp": "quickbooks",
                "reason": "credit_amount_exceeds_remaining_credit",
                "credit_note_number": credit_note_number,
                "remaining_credit": round(remaining_credit, 2),
            }
    except (TypeError, ValueError):
        pass

    vendor_credit_id = str((vendor_credit or {}).get("credit_note_id") or "").strip()
    expense_account = get_account_code("quickbooks", "expenses", gl_map)
    # Intuit's requestid query param is the canonical idempotency
    # mechanism — without it, a transient timeout + retry creates a
    # second VendorCredit + BillPayment in the customer's QBO. Two
    # distinct keys (one per leg) so a partial-success retry resumes
    # cleanly rather than mis-targeting a single key across legs.
    _idem_key = str(idempotency_key or "")[:50] if idempotency_key else ""
    _credit_idem = (
        f"?requestid={_idem_key}:credit" if _idem_key else ""
    )
    _payment_idem = (
        f"?requestid={_idem_key}:payment" if _idem_key else ""
    )
    try:
        client = get_http_client()
        if not vendor_credit_id:
            credit_url = (
                f"https://quickbooks.api.intuit.com/v3/company/"
                f"{connection.realm_id}/vendorcredit{_credit_idem}"
            )
            credit_payload = {
                "VendorRef": {"value": bill["vendor_id"]},
                "APAccountRef": {"value": bill["ap_account_id"]},
                "TxnDate": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                "DocNumber": credit_note_number[:21],
                "PrivateNote": str(
                    application.note or f"Vendor credit {credit_note_number} for bill {bill.get('doc_number') or target_ref}"
                )[:4000],
                "Line": [
                    {
                        "Amount": round(float(application.amount or 0.0), 2),
                        "DetailType": "AccountBasedExpenseLineDetail",
                        "AccountBasedExpenseLineDetail": {
                            "AccountRef": {"value": expense_account},
                        },
                    }
                ],
            }
            credit_response = await client.post(
                credit_url,
                json=credit_payload,
                headers=_quickbooks_headers(connection),
                timeout=30,
            )
            if credit_response.status_code == 401:
                return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}
            credit_response.raise_for_status()
            credit_result = credit_response.json().get("VendorCredit", {})
            vendor_credit_id = str(credit_result.get("Id") or "").strip()
            if not vendor_credit_id:
                return {"status": "error", "erp": "quickbooks", "reason": "no_vendor_credit_returned"}

        payment_url = (
            f"https://quickbooks.api.intuit.com/v3/company/"
            f"{connection.realm_id}/billpayment{_payment_idem}"
        )
        payment_payload = {
            "VendorRef": {"value": bill["vendor_id"]},
            "TotalAmt": round(float(application.amount or 0.0), 2),
            "Line": [
                {
                    "Amount": round(float(application.amount or 0.0), 2),
                    "LinkedTxn": [
                        {"TxnId": target_ref, "TxnType": "Bill"},
                        {"TxnId": vendor_credit_id, "TxnType": "VendorCredit"},
                    ],
                }
            ],
        }
        payment_response = await client.post(
            payment_url,
            json=payment_payload,
            headers=_quickbooks_headers(connection),
            timeout=30,
        )
        if payment_response.status_code == 401:
            return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}
        payment_response.raise_for_status()
        bill_payment = payment_response.json().get("BillPayment", {})
        payment_id = bill_payment.get("Id")
        if not payment_id:
            return {"status": "error", "erp": "quickbooks", "reason": "no_bill_payment_returned"}
        return {
            "status": "success",
            "erp": "quickbooks",
            "erp_reference": payment_id,
            "payment_id": payment_id,
            "target_erp_reference": target_ref,
            "credit_note_reference": vendor_credit_id,
            "credit_note_number": credit_note_number,
            "amount": round(float(application.amount or 0.0), 2),
            "idempotency_key": idempotency_key,
        }
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("QuickBooks credit application HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            payload = e.response.json()
        except Exception:
            payload = None
        fault = _extract_quickbooks_fault_message(payload)
        if fault:
            reason = fault
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("QuickBooks credit application error: %s", type(e).__name__)
        return {"status": "error", "erp": "quickbooks", "reason": "credit_application_failed"}


# ==================== Settlement ====================

async def apply_settlement_to_quickbooks(
    connection,
    application,
    *,
    gl_map: Optional[Dict[str, str]] = None,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """Create a QuickBooks bill payment against a posted bill."""
    from solden.integrations.erp_router import get_account_code

    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not properly configured"}

    source_document_type = str(application.source_document_type or "").strip().lower()
    if source_document_type == "refund":
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "refund_settlement_api_not_available_for_connector",
        }

    missing_fields = []
    target_ref = str(application.target_erp_reference or "").strip()
    if not target_ref:
        missing_fields.append("target_erp_reference")
    if float(application.amount or 0.0) <= 0:
        missing_fields.append("amount")
    if missing_fields:
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "quickbooks_settlement_validation_failed",
            "missing_fields": missing_fields,
        }

    # Late-bound through erp_router so test patches on erp_router.* propagate.
    from solden.integrations import erp_router as _router
    bill = await _router.get_bill_quickbooks(connection, target_ref)
    if bill.get("status") != "success":
        return bill
    if not bill.get("vendor_id"):
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "bill_vendor_not_resolved",
            "target_erp_reference": target_ref,
        }

    payment_payload = {
        "VendorRef": {"value": bill["vendor_id"]},
        "PayType": "Check",
        "CheckPayment": {
            "BankAccountRef": {"value": get_account_code("quickbooks", "cash", gl_map)},
        },
        "TotalAmt": round(float(application.amount or 0.0), 2),
        "Line": [
            {
                "Amount": round(float(application.amount or 0.0), 2),
                "LinkedTxn": [{"TxnId": target_ref, "TxnType": "Bill"}],
            }
        ],
    }
    if application.source_reference:
        payment_payload["PrivateNote"] = str(application.source_reference)[:4000]

    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/billpayment"
    if idempotency_key:
        # Intuit's requestid is the canonical retry-dedupe mechanism.
        url = f"{url}?requestid={str(idempotency_key)[:50]}"
    try:
        client = get_http_client()
        response = await client.post(
            url,
            json=payment_payload,
            headers=_quickbooks_headers(connection),
            timeout=30,
        )
        if response.status_code == 401:
            return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}

        response.raise_for_status()
        bill_payment = response.json().get("BillPayment", {})
        payment_id = bill_payment.get("Id")
        if not payment_id:
            return {"status": "error", "erp": "quickbooks", "reason": "no_bill_payment_returned"}
        return {
            "status": "success",
            "erp": "quickbooks",
            "erp_reference": payment_id,
            "payment_id": payment_id,
            "target_erp_reference": target_ref,
            "amount": round(float(application.amount or 0.0), 2),
            "source_reference": application.source_reference,
            "idempotency_key": idempotency_key,
        }
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("QuickBooks settlement payment HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            payload = e.response.json()
        except Exception:
            payload = None
        fault = _extract_quickbooks_fault_message(payload)
        if fault:
            reason = fault
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("QuickBooks settlement payment error: %s", type(e).__name__)
        return {"status": "error", "erp": "quickbooks", "reason": "settlement_application_failed"}


# ==================== Vendor Management ====================

async def create_vendor_quickbooks(
    connection,
    vendor,
) -> Dict[str, Any]:
    """Create vendor in QuickBooks."""
    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not configured"}

    qb_vendor = {
        "DisplayName": vendor.name,
        "PrintOnCheckName": vendor.name,
    }

    if vendor.email:
        qb_vendor["PrimaryEmailAddr"] = {"Address": vendor.email}
    if vendor.phone:
        qb_vendor["PrimaryPhone"] = {"FreeFormNumber": vendor.phone}
    if vendor.tax_id:
        qb_vendor["TaxIdentifier"] = vendor.tax_id

    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/vendor"

    try:
        client = get_http_client()
        response = await client.post(
            url,
            json=qb_vendor,
            headers={
                "Authorization": f"Bearer {connection.access_token}",
                "Content-Type": "application/json",
            },
            timeout=30,
        )
        response.raise_for_status()
        result = response.json()

        vendor_data = result.get("Vendor", {})
        return {
            "status": "success",
            "vendor_id": vendor_data.get("Id"),
            "display_name": vendor_data.get("DisplayName"),
        }
    except Exception as e:
        logger.error("QuickBooks vendor creation error: %s", type(e).__name__)
        return {"status": "error", "erp": "quickbooks", "reason": "vendor_creation_failed"}


async def find_vendor_quickbooks(
    connection,
    name: Optional[str] = None,
    email: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Find vendor in QuickBooks by name or email."""
    if not connection.access_token or not connection.realm_id:
        return None

    # Build query via canonical helper with strict operand sanitization.
    name_operand = _sanitize_quickbooks_like_operand(name)
    email_operand = _sanitize_quickbooks_like_operand(email)
    query = _build_quickbooks_vendor_lookup_query(
        name_operand=name_operand,
        email_operand=email_operand,
    )
    if not query:
        return None

    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"

    try:
        client = get_http_client()
        response = await client.get(
            url,
            params={"query": query},
            headers={"Authorization": f"Bearer {connection.access_token}"},
            timeout=30,
        )
        response.raise_for_status()
        result = response.json()

        vendors = result.get("QueryResponse", {}).get("Vendor", [])
        if vendors:
            v = vendors[0]
            return {
                "vendor_id": v.get("Id"),
                "name": v.get("DisplayName"),
                "email": v.get("PrimaryEmailAddr", {}).get("Address"),
            }
    except Exception as e:
        logger.error(f"QuickBooks vendor search error: {e}")

    return None


# ==================== Bill Finder ====================

async def find_bill_quickbooks(
    connection,
    invoice_number: str,
) -> Optional[Dict[str, Any]]:
    """Check if a bill with this invoice number already exists in QuickBooks."""
    if not connection.access_token or not connection.realm_id:
        return None
    safe_number = _sanitize_quickbooks_like_operand(invoice_number)
    if not safe_number:
        return None
    literal = _escape_query_literal(safe_number)
    query = f"SELECT Id, DocNumber, TotalAmt FROM Bill WHERE DocNumber = '{literal}'"
    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    try:
        client = get_http_client()
        response = await client.get(
            url,
            params={"query": query},
            headers={"Authorization": f"Bearer {connection.access_token}"},
            timeout=30,
        )
        response.raise_for_status()
        bills = response.json().get("QueryResponse", {}).get("Bill", [])
        if bills:
            b = bills[0]
            return {
                "bill_id": b.get("Id"),
                "doc_number": b.get("DocNumber"),
                "amount": b.get("TotalAmt"),
                "erp": "quickbooks",
            }
    except Exception as e:
        logger.error("QuickBooks bill lookup error: %s", e)
    return None


# ==================== Attachment ====================

async def _attach_to_quickbooks(
    connection, bill_id: str, file_bytes: bytes, filename: str,
) -> Optional[Dict[str, Any]]:
    """Upload attachment to a QuickBooks Bill via the Attachable API."""
    import io
    import json

    creds = connection.credentials or {}
    access_token = creds.get("access_token", "")
    realm_id = creds.get("realm_id", "")
    base_url = creds.get("base_url", "https://quickbooks.api.intuit.com")
    if not access_token or not realm_id:
        return None
    url = f"{base_url}/v3/company/{realm_id}/upload?minorversion=73"
    headers = {"Authorization": f"Bearer {access_token}", "Accept": "application/json"}
    files = {"file_content_01": (filename, io.BytesIO(file_bytes), "application/pdf")}
    metadata = json.dumps({
        "AttachableRef": [{"EntityRef": {"type": "Bill", "value": bill_id}}],
        "FileName": filename,
        "ContentType": "application/pdf",
    })
    client = get_http_client()
    resp = await client.post(url, headers=headers, files=files, data={"file_metadata_01": metadata}, timeout=30)
    resp.raise_for_status()
    return {"attached": True, "erp": "quickbooks"}


# ==================== Payment Status Lookup ====================

async def get_payment_status_quickbooks(
    connection,
    bill_id: str,
) -> Dict[str, Any]:
    """Read payment status for a QuickBooks bill. GET only — never executes payments.

    Checks the Bill's Balance field: Balance == 0 means fully paid.
    If Balance < TotalAmt but > 0, it's a partial payment.
    """
    if not connection.access_token or not connection.realm_id:
        return {"paid": False, "error": "QuickBooks not properly configured"}

    safe_id = _sanitize_quickbooks_like_operand(bill_id)
    if not safe_id:
        return {"paid": False, "error": "invalid_bill_reference"}
    literal = _escape_query_literal(safe_id)
    query = (
        "SELECT Id, DocNumber, TotalAmt, Balance, VendorRef "
        f"FROM Bill WHERE Id = '{literal}'"
    )
    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    try:
        client = get_http_client()
        response = await client.get(
            url,
            params={"query": query},
            headers={"Authorization": f"Bearer {connection.access_token}"},
            timeout=30,
        )
        if response.status_code == 401:
            return {"paid": False, "error": "token_expired", "needs_reauth": True}

        response.raise_for_status()
        bills = response.json().get("QueryResponse", {}).get("Bill", [])
        if not bills:
            return {"paid": False, "reason": "not_found"}

        bill = bills[0]
        total_amt = float(bill.get("TotalAmt") or 0)
        balance = float(bill.get("Balance") or 0)
        bill_id_val = bill.get("Id") or ""

        if balance <= 0 and total_amt > 0:
            # Fully paid — derive closure_method from the bill's
            # LinkedTxn rows (BillPayment vs VendorCredit). The dedicated
            # BillPayment/VendorCredit Query API would give a richer
            # answer but isn't required for the closure-method label.
            closure_method = "payment"
            try:
                if not bill.get("LinkedTxn"):
                    closure_method = "unknown_non_payment"
                else:
                    linked = bill.get("LinkedTxn") or []
                    has_payment = any(
                        str(lt.get("TxnType") or "").lower() == "billpayment"
                        for lt in (linked if isinstance(linked, list) else [])
                    )
                    has_credit = any(
                        str(lt.get("TxnType") or "").lower() in ("vendorcredit", "creditcardcredit")
                        for lt in (linked if isinstance(linked, list) else [])
                    )
                    if has_credit and not has_payment:
                        closure_method = "credit_applied"
                    elif has_payment:
                        closure_method = "payment"
                    else:
                        closure_method = "unknown_non_payment"
            except Exception:
                pass  # Fall through with default closure_method

            result = {
                "paid": True,
                "payment_amount": round(total_amt, 2),
                "payment_date": "",
                "payment_method": "",
                "payment_reference": bill_id_val,
                "partial": False,
                "remaining_balance": 0.0,
            }
            if closure_method != "payment":
                result["closure_method"] = closure_method
            return result

        elif balance < total_amt:
            # Partial payment
            paid_amount = round(total_amt - balance, 2)
            return {
                "paid": False,
                "payment_amount": paid_amount,
                "payment_date": "",
                "payment_method": "",
                "payment_reference": bill_id_val,
                "partial": True,
                "remaining_balance": round(balance, 2),
            }
        else:
            # Check for voided payments (Balance == TotalAmt but voided
            # BillPayments exist in LinkedTxn)
            linked = bill.get("LinkedTxn") or []
            if isinstance(linked, list):
                has_voided = any(
                    str(lt.get("TxnType") or "").lower() == "billpayment"
                    for lt in linked
                )
                if has_voided and balance >= total_amt and total_amt > 0:
                    return {
                        "paid": False,
                        "payment_failed": True,
                        "reason": "payment_voided",
                    }
            return {"paid": False, "reason": "unpaid"}
    except httpx.HTTPStatusError as e:
        logger.error("QuickBooks payment status HTTP error: status=%d", e.response.status_code)
        return {"paid": False, "error": f"http_{e.response.status_code}"}
    except Exception as e:
        logger.error("QuickBooks payment status error: %s", type(e).__name__)
        return {"paid": False, "error": "payment_status_lookup_failed"}


# ==================== BillPayment Fetch (Wave 2 / C3) ====================


async def fetch_quickbooks_bill_payment(
    connection,
    bill_payment_id: str,
) -> Dict[str, Any]:
    """Fetch a BillPayment by its QuickBooks Id.

    Used by the inbound payment webhook receiver: when QB pushes a
    notification of a BillPayment.create / .update event we follow up
    with this read so we know which Bill(s) it cleared, the rail
    (Check / CreditCard), the date, and the cleared amount.

    Returns either::

        {
            "status": "success",
            "bill_payment_id": str,
            "txn_date": str | None,         # YYYY-MM-DD
            "total_amount": float,
            "currency": str | None,         # ISO 4217 from CurrencyRef
            "private_note": str | None,
            "pay_type": str | None,         # "Check" | "CreditCard" | ...
            "linked_bills": [{"bill_id": str, "amount": float}, ...],
            "voided": bool,                 # True if PrivateNote indicates void
        }

    or::

        {"status": "error", "reason": str, "needs_reauth": bool}
    """
    if not connection.access_token or not connection.realm_id:
        return {
            "status": "error",
            "reason": "QuickBooks not properly configured",
        }

    safe_id = _sanitize_quickbooks_like_operand(bill_payment_id)
    if not safe_id:
        return {"status": "error", "reason": "invalid_bill_payment_id"}

    url = (
        f"https://quickbooks.api.intuit.com/v3/company/"
        f"{connection.realm_id}/billpayment/{safe_id}"
    )
    try:
        client = get_http_client()
        response = await client.get(
            url,
            headers=_quickbooks_headers(connection),
            timeout=_ERP_TIMEOUT,
        )
        if response.status_code == 401:
            return {
                "status": "error",
                "reason": "token_expired",
                "needs_reauth": True,
            }
        if response.status_code == 404:
            return {"status": "error", "reason": "not_found"}
        response.raise_for_status()
        body = response.json() or {}
        bp = body.get("BillPayment") or {}
        if not bp:
            return {"status": "error", "reason": "no_bill_payment_in_response"}

        linked: List[Dict[str, Any]] = []
        for line in bp.get("Line") or []:
            if not isinstance(line, dict):
                continue
            line_amount = line.get("Amount")
            for lt in line.get("LinkedTxn") or []:
                if not isinstance(lt, dict):
                    continue
                if str(lt.get("TxnType") or "").lower() != "bill":
                    continue
                tid = str(lt.get("TxnId") or "").strip()
                if tid:
                    linked.append({
                        "bill_id": tid,
                        "amount": (
                            float(line_amount)
                            if line_amount is not None else None
                        ),
                    })

        currency = None
        currency_ref = bp.get("CurrencyRef")
        if isinstance(currency_ref, dict):
            currency = currency_ref.get("value") or None

        private_note = bp.get("PrivateNote")
        pay_type = str(bp.get("PayType") or "").strip() or None

        # QB doesn't expose a "Voided" flag directly on BillPayment;
        # convention is to set PrivateNote to "Voided" when voiding.
        voided = bool(
            isinstance(private_note, str)
            and "void" in private_note.lower()
        )

        return {
            "status": "success",
            "bill_payment_id": str(bp.get("Id") or safe_id),
            "txn_date": bp.get("TxnDate"),
            "total_amount": float(bp.get("TotalAmt") or 0.0),
            "currency": currency,
            "private_note": private_note,
            "pay_type": pay_type,
            "linked_bills": linked,
            "voided": voided,
        }
    except httpx.HTTPStatusError as exc:
        sc = exc.response.status_code
        return {"status": "error", "reason": f"http_{sc}"}
    except Exception as exc:
        logger.warning(
            "fetch_quickbooks_bill_payment failed: %s",
            type(exc).__name__,
        )
        return {"status": "error", "reason": "bill_payment_fetch_failed"}


# ==================== Tax Code Default Map ====================

# Default Solden vat_code -> QuickBooks TaxCode id. The TaxCode
# entity is per-realm in QBO, so these defaults are best-effort —
# operators override per-realm via settings_json[gl_account_map]
# [tax_code_T1] = "<realm-specific TaxCode id>".
# QB Sandbox / US realms typically use "TAX" / "NON" as id strings;
# UK / EU realms use numeric ids (e.g. "9" for Standard Rated).
_DEFAULT_QB_TAXCODE_MAP: Dict[str, str] = {
    "T1": "TAX",   # Taxable
    "T0": "NON",   # Non-taxable / zero-rated
    "T2": "NON",   # Exempt
    "RC": "NON",   # Reverse charge — net to vendor (no QBO tax line)
    "OO": "NON",   # Out of scope
}


# ==================== Chart of Accounts ====================

_QB_ACCOUNT_TYPE_MAP = {
    "bank": "asset",
    "other current asset": "asset",
    "fixed asset": "asset",
    "other asset": "asset",
    "accounts receivable": "asset",
    "accounts payable": "liability",
    "credit card": "liability",
    "other current liability": "liability",
    "long term liability": "liability",
    "equity": "equity",
    "income": "revenue",
    "other income": "revenue",
    "expense": "expense",
    "other expense": "expense",
    "cost of goods sold": "expense",
}


async def get_chart_of_accounts_quickbooks(connection) -> List[Dict[str, Any]]:
    """Fetch all accounts from QuickBooks Online.

    Returns a normalized list of account dicts.  Returns ``[]`` on any error
    so the caller is never blocked.
    """
    if not connection.access_token or not connection.realm_id:
        return []

    url = (
        f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    )
    try:
        client = get_http_client()
        response = await client.get(
            url,
            params={"query": "SELECT * FROM Account MAXRESULTS 1000"},
            headers=_quickbooks_headers(connection),
            timeout=60,
        )

        if response.status_code == 401:
            logger.warning("QuickBooks token expired during chart-of-accounts fetch")
            return []

        response.raise_for_status()
        result = response.json()

        accounts: List[Dict[str, Any]] = []
        for acc in result.get("QueryResponse", {}).get("Account", []):
            raw_type = str(acc.get("AccountType") or "").strip().lower()
            accounts.append({
                "id": str(acc.get("Id") or ""),
                "code": str(acc.get("AcctNum") or ""),
                "name": str(acc.get("Name") or ""),
                "type": _QB_ACCOUNT_TYPE_MAP.get(raw_type, raw_type),
                "sub_type": str(acc.get("AccountSubType") or ""),
                "active": acc.get("Active", True) is True,
                "currency": str(acc.get("CurrencyRef", {}).get("value", "") if isinstance(acc.get("CurrencyRef"), dict) else ""),
            })
        return accounts

    except Exception as e:
        logger.error("Failed to fetch QuickBooks chart of accounts: %s", type(e).__name__)
        return []


# ==================== Vendor List ====================


async def list_all_vendors_quickbooks(connection) -> List[Dict[str, Any]]:
    """Fetch all vendors from QuickBooks Online with pagination.

    QuickBooks Query API uses STARTPOSITION (1-based) and MAXRESULTS.
    Returns a normalized list of vendor dicts.  Returns ``[]`` on any error.
    """
    if not connection.access_token or not connection.realm_id:
        return []

    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    page_size = 1000
    start_position = 1
    all_vendors: List[Dict[str, Any]] = []

    try:
        client = get_http_client()
        while True:
            query = (
                f"SELECT * FROM Vendor STARTPOSITION {start_position} "
                f"MAXRESULTS {page_size}"
            )
            response = await client.get(
                url,
                params={"query": query},
                headers=_quickbooks_headers(connection),
                timeout=60,
            )

            if response.status_code == 401:
                logger.warning("QuickBooks token expired during vendor list fetch")
                break

            response.raise_for_status()
            result = response.json()

            vendors = result.get("QueryResponse", {}).get("Vendor", [])
            if not vendors:
                break

            for v in vendors:
                addr = v.get("BillAddr") or {}
                all_vendors.append({
                    "vendor_id": str(v.get("Id") or ""),
                    "name": str(v.get("DisplayName") or ""),
                    "email": str((v.get("PrimaryEmailAddr") or {}).get("Address") or ""),
                    "phone": str((v.get("PrimaryPhone") or {}).get("FreeFormNumber") or ""),
                    "tax_id": str(v.get("TaxIdentifier") or ""),
                    "currency": str((v.get("CurrencyRef") or {}).get("value") or ""),
                    "active": v.get("Active", True) is True,
                    "address": ", ".join(
                        filter(None, [
                            addr.get("Line1"), addr.get("City"),
                            addr.get("CountrySubDivisionCode"), addr.get("PostalCode"),
                            addr.get("Country"),
                        ])
                    ),
                    "payment_terms": "",
                    "balance": float(v.get("Balance") or 0),
                })

            if len(vendors) < page_size:
                break
            start_position += page_size

        return all_vendors

    except Exception as e:
        logger.error("Failed to fetch QuickBooks vendor list: %s", type(e).__name__)
        return all_vendors or []


async def list_all_purchase_orders_quickbooks(connection) -> List[Dict[str, Any]]:
    """Fetch all Purchase Orders from QuickBooks Online with pagination.

    Returns normalized dicts compatible with PurchaseOrderStore.save_purchase_order.
    Only OPEN POs (not closed/cancelled) come back — those are the
    only ones invoice matching should consider. Returns [] on any error.
    """
    if not connection.access_token or not connection.realm_id:
        return []

    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    page_size = 1000
    start_position = 1
    all_pos: List[Dict[str, Any]] = []

    def _status_from_qb(po: Dict[str, Any]) -> str:
        """Map QuickBooks PO state to our POStatus values."""
        status = str(po.get("POStatus") or "").strip().lower()
        tx_status = str(po.get("TxnStatus") or "").strip().lower()
        if status == "closed" or tx_status == "closed":
            return "closed"
        # QB doesn't track receipt/invoice progress against POs directly;
        # match_invoice_to_po advances our copy when the invoice posts.
        # Treat everything else as "approved" (i.e. matchable).
        return "approved"

    try:
        client = get_http_client()
        while True:
            query = (
                f"SELECT * FROM PurchaseOrder STARTPOSITION {start_position} "
                f"MAXRESULTS {page_size}"
            )
            response = await client.get(
                url,
                params={"query": query},
                headers=_quickbooks_headers(connection),
                timeout=60,
            )
            if response.status_code == 401:
                logger.warning("QuickBooks token expired during PO list fetch")
                break
            response.raise_for_status()
            result = response.json()
            pos = result.get("QueryResponse", {}).get("PurchaseOrder", [])
            if not pos:
                break
            for po in pos:
                vendor_ref = po.get("VendorRef") or {}
                lines = []
                for li in (po.get("Line") or []):
                    detail = li.get("ItemBasedExpenseLineDetail") or li.get(
                        "AccountBasedExpenseLineDetail"
                    ) or {}
                    item_ref = detail.get("ItemRef") or {}
                    acct_ref = detail.get("AccountRef") or {}
                    lines.append({
                        "line_id": str(li.get("Id") or ""),
                        "item_number": str(item_ref.get("value") or ""),
                        "description": str(li.get("Description") or item_ref.get("name") or acct_ref.get("name") or ""),
                        "quantity": float(detail.get("Qty") or 0.0),
                        "unit_price": float(detail.get("UnitPrice") or 0.0),
                        "gl_code": str(acct_ref.get("value") or ""),
                    })
                all_pos.append({
                    "po_id": f"qb-po-{po.get('Id')}",
                    "po_number": str(po.get("DocNumber") or ""),
                    "vendor_id": str(vendor_ref.get("value") or ""),
                    "vendor_name": str(vendor_ref.get("name") or ""),
                    "order_date": str(po.get("TxnDate") or ""),
                    "expected_delivery": str(po.get("DueDate") or "") or None,
                    "line_items": lines,
                    "subtotal": float(po.get("TotalAmt") or 0.0),
                    "tax_amount": 0.0,
                    "total_amount": float(po.get("TotalAmt") or 0.0),
                    "currency": str((po.get("CurrencyRef") or {}).get("value") or "USD"),
                    "status": _status_from_qb(po),
                    "requested_by": "quickbooks_sync",
                    "erp_po_id": str(po.get("Id") or ""),
                })
            if len(pos) < page_size:
                break
            start_position += page_size

        return all_pos

    except Exception as e:
        logger.error("Failed to fetch QuickBooks PO list: %s", type(e).__name__)
        return all_pos or []
