"""
NetSuite ERP Integration

All NetSuite-specific API calls: journal entries, bills, vendors, credits,
settlements, attachments, OAuth 1.0 header construction, and async polling.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import httpx
from solden.core.http_client import get_http_client

from solden.core.money import money_to_float
from solden.integrations.erp_sanitization import (
    _build_netsuite_vendor_lookup_query,
    _escape_query_literal,
    _sanitize_netsuite_email_operand,
    _sanitize_netsuite_like_operand,
)

logger = logging.getLogger(__name__)

_ERP_TIMEOUT = 30


def _oauth_header(connection, method: str, url: str) -> str:
    """Resolve build_netsuite_oauth_header through erp_router so test patches propagate."""
    import sys
    router = sys.modules.get("solden.integrations.erp_router")
    if router is not None:
        return router.build_netsuite_oauth_header(connection, method, url)
    return build_netsuite_oauth_header(connection, method, url)


def _extract_netsuite_validation_message(payload: Optional[Dict[str, Any]]) -> Optional[str]:
    if not isinstance(payload, dict):
        return None
    for key in ("o:errorMessage", "error", "message", "title"):
        message = str(payload.get(key) or "").strip()
        if message:
            return message
    for key in ("o:errorDetails", "errorDetails", "details", "errors"):
        details = payload.get(key)
        if not isinstance(details, list):
            continue
        for entry in details:
            if not isinstance(entry, dict):
                continue
            for detail_key in ("detail", "message", "o:errorDetail", "title"):
                detail = str(entry.get(detail_key) or "").strip()
                if detail:
                    return detail
    return None


# ==================== OAuth ====================

def build_netsuite_oauth_header(
    connection,
    method: str,
    url: str,
) -> str:
    """
    Build OAuth 1.0 Authorization header for NetSuite TBA.

    NetSuite uses Token-Based Authentication which is OAuth 1.0 based.
    """
    import base64
    import hashlib
    import hmac
    import time
    import urllib.parse
    import uuid

    # OAuth parameters
    oauth_params = {
        "oauth_consumer_key": connection.consumer_key or "",
        "oauth_token": connection.token_id or "",
        "oauth_signature_method": "HMAC-SHA256",
        "oauth_timestamp": str(int(time.time())),
        "oauth_nonce": str(uuid.uuid4()).replace("-", ""),
        "oauth_version": "1.0",
        "realm": connection.account_id or "",
    }

    # Build base string
    param_string = "&".join(
        f"{urllib.parse.quote(k, safe='')}={urllib.parse.quote(v, safe='')}"
        for k, v in sorted(oauth_params.items())
        if k != "realm"
    )

    base_string = "&".join([
        method.upper(),
        urllib.parse.quote(url, safe=""),
        urllib.parse.quote(param_string, safe=""),
    ])

    # Build signing key
    signing_key = "&".join([
        urllib.parse.quote(connection.consumer_secret or "", safe=""),
        urllib.parse.quote(connection.token_secret or "", safe=""),
    ])

    # Generate signature
    signature = base64.b64encode(
        hmac.new(
            signing_key.encode("utf-8"),
            base_string.encode("utf-8"),
            hashlib.sha256,
        ).digest()
    ).decode("utf-8")

    oauth_params["oauth_signature"] = signature

    # Build header
    auth_header = "OAuth " + ", ".join(
        f'{k}="{urllib.parse.quote(v, safe="")}"'
        for k, v in oauth_params.items()
    )

    return auth_header


# ==================== Journal Entry ====================

async def post_to_netsuite(
    connection,
    entry: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Post journal entry to NetSuite via REST API.

    NetSuite uses Token-Based Authentication (TBA) with OAuth 1.0.

    API Docs:
    https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1544787084.html
    """
    if not connection.account_id:
        return {"status": "error", "erp": "netsuite", "reason": "NetSuite account ID not configured"}

    # Build NetSuite journal entry format
    ns_entry = {
        "tranDate": entry.get("date", datetime.now(timezone.utc).strftime("%Y-%m-%d")),
        "memo": entry.get("description", "Auto-generated by Solden"),
        "subsidiary": {"id": "1"},  # Default subsidiary
        "line": {
            "items": []
        },
    }

    line_num = 0
    for line in entry.get("lines", []):
        debit = line.get("debit", 0)
        credit = line.get("credit", 0)

        ns_line = {
            "lineId": line_num,
            "account": {"id": line.get("account", "1")},
            "memo": line.get("account_name", ""),
        }

        if debit > 0:
            ns_line["debit"] = debit
        else:
            ns_line["credit"] = credit

        ns_entry["line"]["items"].append(ns_line)
        line_num += 1

    # Build OAuth 1.0 signature for NetSuite TBA
    auth_header = _oauth_header(
        connection,
        "POST",
        f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/record/v1/journalEntry",
    )

    try:
        client = get_http_client()
        response = await client.post(
            f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/record/v1/journalEntry",
            json=ns_entry,
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
                "Prefer": "respond-async, transient",
            },
            timeout=60,
        )

        if response.status_code == 401:
            logger.warning("NetSuite authentication failed")
            return {"status": "error", "erp": "netsuite", "reason": "Authentication failed", "needs_reauth": True}

        response.raise_for_status()
        result = response.json()

        entry_id = result.get("id") or result.get("internalId")
        logger.info(f"Posted to NetSuite: {entry_id}")

        return {
            "status": "success",
            "erp": "netsuite",
            "entry_id": entry_id,
            "tran_id": result.get("tranId"),
        }

    except httpx.HTTPStatusError as e:
        logger.error("NetSuite API error: %s", e.response.status_code)
        return {"status": "error", "erp": "netsuite", "reason": f"NetSuite API {e.response.status_code}"}
    except Exception as e:
        logger.error("NetSuite error: %s", type(e).__name__)
        return {"status": "error", "erp": "netsuite", "reason": "posting_failed"}


# ==================== Accounts ====================

async def get_netsuite_accounts(connection) -> List[Dict[str, Any]]:
    """
    Get chart of accounts from NetSuite.

    Useful for GL account mapping during onboarding.
    """
    if not connection.account_id:
        return []

    auth_header = _oauth_header(
        connection,
        "GET",
        f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/record/v1/account",
    )

    try:
        client = get_http_client()
        response = await client.get(
            f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/record/v1/account",
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
            },
            params={"limit": 1000},
            timeout=60,
        )
        response.raise_for_status()
        result = response.json()

        accounts = []
        for item in result.get("items", []):
            accounts.append({
                "id": item.get("id"),
                "name": item.get("acctName"),
                "number": item.get("acctNumber"),
                "type": item.get("acctType", {}).get("refName"),
            })

        return accounts

    except Exception as e:
        logger.error(f"Failed to get NetSuite accounts: {e}")
        return []


# ==================== Async Polling ====================

async def _poll_netsuite_async_result(
    client: httpx.AsyncClient,
    *,
    auth_header: str,
    location: str,
) -> Optional[Dict[str, Any]]:
    import asyncio as _asyncio

    for _attempt in range(5):
        await _asyncio.sleep(2)
        poll_resp = await client.get(
            location,
            headers={"Authorization": auth_header},
            timeout=30,
        )
        if poll_resp.status_code == 200:
            return poll_resp.json()
        if poll_resp.status_code != 202:
            break
    return None


# ==================== Bill Posting ====================

async def post_bill_to_netsuite(
    connection,
    bill,
    gl_map: Optional[Dict[str, str]] = None,
    field_mappings: Optional[Dict[str, str]] = None,
    custom_fields: Optional[Dict[str, str]] = None,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Post vendor bill to NetSuite.

    API: https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/record_vendorbill.html

    ``field_mappings`` (Module 5) lets the customer rename standard
    dimension fields (department/class/location). ``custom_fields``
    is the resolved {erp_field_id: value} dict for workflow custom
    body fields (state/box_id/approver/correlation_id) — the agent
    stamps these onto the outbound Vendor Bill so NetSuite reports
    can filter on Solden-managed work.
    """
    from solden.integrations.erp_router import get_account_code, _dimension_field_name

    if not connection.account_id:
        return {"status": "error", "erp": "netsuite", "reason": "NetSuite account ID not configured"}

    # Pre-flight validation — symmetric to ``post_bill_to_sap``'s
    # ``sap_validation_failed`` shape. Pre-fix, NetSuite let
    # missing-vendor / zero-amount / missing-subsidiary bills reach
    # the API and returned a generic NetSuite error code. Operator
    # dashboards that parse SAP's ``missing_fields`` list saw nothing
    # for NetSuite. Now both adapters return the same shape:
    #   {"status": "error", "reason": "<erp>_validation_failed",
    #    "missing_fields": [...]}
    missing_fields: List[str] = []
    if not getattr(bill, "vendor_id", None):
        missing_fields.append("vendor_id")
    try:
        _amt = float(getattr(bill, "amount", 0) or 0)
    except (TypeError, ValueError):
        _amt = 0.0
    if _amt <= 0:
        missing_fields.append("amount")
    # Currency is OPTIONAL on NetSuite Vendor Bill — when omitted,
    # NetSuite uses the subsidiary's default. We only flag it as
    # invalid when the caller provided something non-empty that's
    # not a 3-letter code (typo guard). Mirror the loose-on-empty,
    # strict-on-malformed pattern.
    bill_currency_validate = str(getattr(bill, "currency", "") or "").strip().upper()
    if bill_currency_validate and len(bill_currency_validate) != 3:
        missing_fields.append("currency")
    # OneWorld tenants require a subsidiary on every Vendor Bill.
    # ``ERPConnection.subsidiary_id`` is set at onboarding for
    # OneWorld accounts; if it's missing on a OneWorld tenant the
    # post will be silently mis-attributed without this guard.
    if (
        bool(getattr(connection, "is_oneworld", False))
        and not getattr(connection, "subsidiary_id", None)
    ):
        missing_fields.append("subsidiary_id")
    if missing_fields:
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": "netsuite_validation_failed",
            "missing_fields": missing_fields,
        }

    # Client-side idempotency pre-check. NetSuite Vendor Bill's
    # ``tranId`` uniqueness is configurable per-account, not enforced
    # by default — concurrent posters with the same idempotency_key
    # could otherwise create duplicate bills. When a key is supplied
    # and the bill has an invoice_number, we look up the existing
    # bill first and short-circuit with ``status=already_posted`` if
    # it's there. Failure of this lookup is non-fatal; we proceed
    # with the post and rely on the audit-event idempotency check
    # (router H10) as a backstop.
    if idempotency_key and getattr(bill, "invoice_number", None):
        try:
            existing_bill = await find_bill_netsuite(
                connection, str(bill.invoice_number),
            )
        except Exception as find_exc:
            logger.debug(
                "[NetSuite] find_bill pre-check failed (proceeding) "
                "vendor=%s invoice=%s: %s",
                getattr(bill, "vendor_name", None),
                bill.invoice_number, find_exc,
            )
            existing_bill = None
        if existing_bill and existing_bill.get("bill_id"):
            return {
                "status": "already_posted",
                "erp": "netsuite",
                "bill_id": existing_bill.get("bill_id"),
                "doc_number": existing_bill.get("doc_number"),
                "amount": existing_bill.get("amount"),
                "idempotency_key": idempotency_key,
            }

    expense_account = get_account_code("netsuite", "expenses", gl_map)

    # Build NetSuite Vendor Bill format
    ns_bill = {
        "entity": {"id": bill.vendor_id},  # Vendor reference
        "tranDate": bill.invoice_date or datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "dueDate": bill.due_date,
        "tranId": bill.invoice_number,  # Vendor's invoice number
        "memo": bill.description or f"Invoice from {bill.vendor_name}",
        "item": {"items": []},
        "expense": {"items": []},
    }

    # Subsidiary (OneWorld tenants only). NetSuite OneWorld requires
    # ``subsidiary`` on every Vendor Bill — single-subsidiary accounts
    # omit the field. We store the configured subsidiary internal ID
    # on ``ERPConnection.subsidiary_id`` at onboarding; if present we
    # attach it here. Bill post will fail with a clear schema error
    # on OneWorld accounts that haven't configured a subsidiary, which
    # is what we want — silent post to the wrong entity is much worse.
    if getattr(connection, "subsidiary_id", None):
        ns_bill["subsidiary"] = {"id": str(connection.subsidiary_id)}

    # Currency. NetSuite references currencies by refName (3-letter
    # ISO code works for most tenants). Some subsidiaries with exotic
    # currencies need internal IDs — if the caller has supplied a
    # NetSuite currency internal ID via gl_map (key:
    # ``currency_id_<CODE>``), prefer that over the refName. This
    # matches the same gl_map convention used for GL account codes.
    bill_currency = str(getattr(bill, "currency", "") or "").strip().upper()
    if bill_currency:
        currency_key = f"currency_id_{bill_currency}"
        if gl_map and gl_map.get(currency_key):
            ns_bill["currency"] = {"id": str(gl_map[currency_key])}
        elif len(bill_currency) == 3:
            ns_bill["currency"] = {"refName": bill_currency}

    # Add line items as expenses. Money boundary: quantize before
    # serialising so what we send to NetSuite matches our internal
    # Decimal value exactly. Per-line tax rate (``tax_rate`` + optional
    # ``tax_code_id``) is attached when provided — required for UK
    # VAT, EU reverse-charge, NG VAT, AU GST reporting. When not
    # provided, we fall back to the lump-sum ``taxTotal`` for tenants
    # that don't break out per-line tax.
    has_per_line_tax = False
    if bill.line_items:
        for i, item in enumerate(bill.line_items):
            line = {
                "line": i + 1,
                "account": {"id": item.get("gl_code") or item.get("account_id") or expense_account},
                "amount": money_to_float(item.get("amount", 0)),
                "memo": item.get("description", ""),
            }
            # Module 5 Pass C — carry per-line dimensions from upstream
            # line_items into the wire payload. NetSuite expects each
            # of these as { "id": <internal_id> }. Renamed below by
            # _dimension_field_name when the customer has overridden
            # the field name.
            for dim_key in ("department", "class", "location"):
                dim_val = item.get(dim_key)
                if dim_val:
                    line[dim_key] = {"id": str(dim_val)}
            line_tax_rate = item.get("tax_rate")
            line_tax_code = item.get("tax_code_id") or item.get("tax_code")
            if line_tax_rate is not None or line_tax_code:
                has_per_line_tax = True
                if line_tax_rate is not None:
                    try:
                        line["taxRate1"] = float(line_tax_rate)
                    except (TypeError, ValueError):
                        pass
                if line_tax_code:
                    line["taxCode"] = {"id": str(line_tax_code)}
                line_tax_amt = item.get("tax_amount")
                if line_tax_amt is not None:
                    line["tax1Amt"] = money_to_float(line_tax_amt)
            ns_bill["expense"]["items"].append(line)
    else:
        ns_bill["expense"]["items"].append({
            "line": 1,
            "account": {"id": expense_account},
            "amount": money_to_float(bill.amount),
            "memo": bill.description or f"Invoice {bill.invoice_number}",
        })

    # Lump-sum tax only when per-line tax isn't present — avoids
    # double-counting when both are set.
    if (
        getattr(bill, "tax_amount", None)
        and bill.tax_amount > 0
        and not has_per_line_tax
    ):
        ns_bill["taxTotal"] = money_to_float(bill.tax_amount)

    # Discount as negative expense line
    if getattr(bill, "discount_amount", None) and bill.discount_amount > 0:
        ns_bill["expense"]["items"].append({
            "line": len(ns_bill["expense"]["items"]) + 1,
            "account": {"id": expense_account},
            "amount": -bill.discount_amount,
            "memo": f"Discount ({getattr(bill, 'discount_terms', '') or 'early payment'})",
        })

    # Payment terms in memo
    if getattr(bill, "payment_terms", None):
        ns_bill["memo"] = f"{ns_bill['memo']} | Terms: {bill.payment_terms}"

    # Module 5 Pass C — stamp customer-configured custom body fields
    # (workflow). Each ``custom_fields`` key is the literal NetSuite
    # field id (e.g. ``custbody_clearledgr_state``); value is the
    # resolved string (state name, box id, approver email,
    # correlation id). Catalog regex restricts ids to safe chars at
    # the API boundary so we can splat into the body without escaping
    # concerns.
    if custom_fields:
        for erp_field_id, value in custom_fields.items():
            if erp_field_id and value is not None:
                ns_bill[str(erp_field_id)] = value

    # Module 5 Pass C — dimension field renames. NetSuite's standard
    # dimensions live on each line ('department', 'class', 'location').
    # Customers with non-default subsidiary configs occasionally rename
    # these — when they do, the customer maps the catalog key to the
    # actual NetSuite field id and we rewrite each line key on the way
    # out. ``field_mappings`` is the raw catalog dict; we resolve only
    # the dimension entries here.
    dimension_renames = {}
    for catalog_key, default in (
        ("department_field", "department"),
        ("class_field", "class"),
        ("location_field", "location"),
    ):
        custom = _dimension_field_name(field_mappings or {}, catalog_key, default)
        if custom != default:
            dimension_renames[default] = custom

    if dimension_renames:
        for line in ns_bill["expense"]["items"]:
            for default_key, custom_key in dimension_renames.items():
                if default_key in line and custom_key != default_key:
                    line[custom_key] = line.pop(default_key)

    url = f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/record/v1/vendorBill"
    auth_header = _oauth_header(connection, "POST", url)

    try:
        client = get_http_client()
        response = await client.post(
            url,
            json=ns_bill,
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
                "Prefer": "respond-async",
            },
            timeout=60,
        )

        if response.status_code == 401:
            return {"status": "error", "erp": "netsuite", "reason": "Authentication failed", "needs_reauth": True}

        response.raise_for_status()

        # H6: Handle async 202 response — poll Location header for result
        if response.status_code == 202:
            location = response.headers.get("Location", "").strip()
            if location:
                # Poll for the result (up to 5 attempts with 2s delay)
                import asyncio as _asyncio
                for _attempt in range(5):
                    await _asyncio.sleep(2)
                    poll_resp = await client.get(
                        location,
                        headers={"Authorization": auth_header},
                        timeout=30,
                    )
                    if poll_resp.status_code == 200:
                        poll_result = poll_resp.json()
                        bill_id = poll_result.get("id") or poll_result.get("internalId")
                        logger.info("Posted Vendor Bill to NetSuite (async): %s", bill_id)
                        # Wave 1 / A2 — NetSuite's Vendor Bill IS the
                        # source transaction record; the GL JE is
                        # auto-derived from this transaction at the
                        # GL layer. Auditor traceability uses the
                        # bill internalid as the journal source id,
                        # the same way ``tran:<id>`` shows up in
                        # NetSuite saved-search journal queries.
                        return {
                            "status": "success",
                            "erp": "netsuite",
                            "bill_id": bill_id,
                            "tran_id": poll_result.get("tranId"),
                            "erp_journal_entry_id": (
                                str(bill_id) if bill_id is not None else None
                            ),
                        }
                    if poll_resp.status_code != 202:
                        break
                logger.warning("NetSuite async job did not complete within polling window")
                return {"status": "error", "erp": "netsuite", "reason": "async_timeout"}
            # No Location header — treat 202 body as best-effort
            logger.warning("NetSuite returned 202 without Location header")

        result = response.json()

        bill_id = result.get("id") or result.get("internalId")
        logger.info("Posted Vendor Bill to NetSuite: %s", bill_id)
        return {
            "status": "success",
            "erp": "netsuite",
            "bill_id": bill_id,
            "tran_id": result.get("tranId"),
            # Wave 1 / A2 — see async branch above for rationale.
            "erp_journal_entry_id": (
                str(bill_id) if bill_id is not None else None
            ),
        }

    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        # Parse NetSuite error response for actionable details
        erp_error_detail = ""
        erp_error_code = ""
        try:
            error_body = e.response.json()
            # NetSuite REST: {"status": {"isSuccess": false, "statusDetail": [{"code": "...", "message": "..."}]}}
            status_obj = error_body.get("status") or {}
            status_details = status_obj.get("statusDetail") or []
            if status_details:
                first = status_details[0]
                erp_error_code = first.get("code") or ""
                erp_error_detail = first.get("message") or ""
            # Fallback: some NetSuite errors use top-level "message" or "error.message"
            if not erp_error_detail:
                ns_error = error_body.get("error") or {}
                if isinstance(ns_error, dict):
                    erp_error_detail = ns_error.get("message") or ""
                    erp_error_code = erp_error_code or (ns_error.get("code") or "")
            if not erp_error_detail:
                erp_error_detail = error_body.get("message") or error_body.get("title") or ""
        except Exception:
            # Memory rule: no raw response bodies in returned values.
            # Log truncated text for debug, return opaque placeholder.
            try:
                _full_text = e.response.text if hasattr(e.response, "text") else ""
            except Exception:
                _full_text = ""
            if _full_text:
                logger.debug(
                    "[NetSuite] non-json error response (truncated): %s",
                    _full_text[:200],
                )
            erp_error_detail = f"http_{status_code}_non_json_response"

        detail_lower = erp_error_detail.lower()
        code_upper = erp_error_code.upper()
        reason = f"http_{status_code}"
        if status_code == 404:
            reason = "erp_configuration_stale"
            logger.error(
                "NetSuite 404 — likely account_id mismatch (account_id=%s). "
                "Verify the account is accessible with current credentials.",
                connection.account_id,
            )
        elif "duplicate" in detail_lower or code_upper == "DUPLICATE_REFERENCE_NUMBER":
            reason = "erp_duplicate_bill"
        elif "invalid account" in detail_lower or code_upper == "INVALID_KEY_OR_REF" and "account" in detail_lower:
            reason = "erp_gl_account_invalid"
        elif "vendor" in detail_lower and ("not found" in detail_lower or "invalid" in detail_lower) or code_upper == "INVALID_KEY_OR_REF" and "vendor" in detail_lower:
            reason = "erp_vendor_not_found"
        elif code_upper == "INVALID_KEY_OR_REF":
            reason = "erp_invalid_reference"

        logger.error(
            "NetSuite Vendor Bill API error: status=%d reason=%s code=%s detail=%s",
            status_code, reason, erp_error_code, erp_error_detail[:200],
        )
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": reason,
            "erp_error_detail": erp_error_detail,
            "erp_error_code": erp_error_code,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("NetSuite Vendor Bill error: %s: %s", type(e).__name__, e)
        return {
            "status": "error", "erp": "netsuite",
            "reason": "bill_posting_failed",
            "erp_error_detail": type(e).__name__,
        }


# ==================== Bill Reversal ====================


async def reverse_bill_from_netsuite(
    connection,
    erp_reference: str,
    *,
    reason: str,
) -> Dict[str, Any]:
    """Reverse a posted NetSuite vendor bill via REST DELETE.

    NetSuite's REST record API supports DELETE on vendorBill records
    provided the bill has not been paid, voided, or used in a reconcile.
    The override-window (Phase 1.4) precondition ensures no payment is
    yet applied for same-session reversals.

    NetSuite's DELETE hard-removes the record. Some accounts configure
    their NetSuite schema to disallow DELETE on transactional records —
    in that case we get a 403 and surface ``cannot_delete_record``.

    On success returns ``reversal_method="delete"`` and ``reversal_ref``
    equal to the original internalId.
    """
    if not connection.account_id:
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": "NetSuite account ID not configured",
        }
    if not erp_reference:
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": "missing_erp_reference",
        }

    url = (
        f"https://{connection.account_id}.suitetalk.api.netsuite.com"
        f"/services/rest/record/v1/vendorBill/{erp_reference}"
    )
    auth_header = _oauth_header(connection, "DELETE", url)

    try:
        client = get_http_client()
        response = await client.delete(
            url,
            headers={
                "Authorization": auth_header,
                "Accept": "application/json",
            },
            timeout=60,
        )

        if response.status_code == 401:
            return {
                "status": "error",
                "erp": "netsuite",
                "reason": "Authentication failed",
                "needs_reauth": True,
            }

        if response.status_code == 404:
            return {
                "status": "already_reversed",
                "erp": "netsuite",
                "reference_id": erp_reference,
                "reversal_method": "delete",
                "reversal_ref": erp_reference,
                "reason": "bill_not_found_in_erp",
            }

        # NetSuite DELETE returns 204 No Content on success
        if response.status_code in (200, 204):
            logger.info(
                "Deleted NetSuite Vendor Bill %s (reason=%s)",
                erp_reference, reason,
            )
            return {
                "status": "success",
                "erp": "netsuite",
                "reference_id": erp_reference,
                "reversal_method": "delete",
                "reversal_ref": erp_reference,
                "erp_status": "Deleted",
            }

        response.raise_for_status()
        # Fallthrough — unexpected success status
        return {
            "status": "success",
            "erp": "netsuite",
            "reference_id": erp_reference,
            "reversal_method": "delete",
            "reversal_ref": erp_reference,
            "erp_status": f"http_{response.status_code}",
        }

    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        erp_error_detail = ""
        erp_error_code = ""
        try:
            error_body = e.response.json() or {}
            status_obj = error_body.get("status") or {}
            status_details = status_obj.get("statusDetail") or []
            if status_details:
                first = status_details[0]
                erp_error_code = first.get("code") or ""
                erp_error_detail = first.get("message") or ""
            if not erp_error_detail:
                ns_error = error_body.get("error") or {}
                if isinstance(ns_error, dict):
                    erp_error_detail = ns_error.get("message") or ""
                    erp_error_code = erp_error_code or (ns_error.get("code") or "")
            if not erp_error_detail:
                erp_error_detail = (
                    error_body.get("message") or error_body.get("title") or ""
                )
        except Exception:
            erp_error_detail = (
                e.response.text[:200] if hasattr(e.response, "text") else ""
            )

        detail_lower = erp_error_detail.lower()
        code_upper = erp_error_code.upper()
        reason_code = f"http_{status_code}"

        if status_code == 403:
            reason_code = "cannot_delete_record"
        elif "paid" in detail_lower or "payment" in detail_lower:
            reason_code = "payment_already_applied"
        elif "closed" in detail_lower and "period" in detail_lower:
            reason_code = "accounting_period_closed"
        elif status_code == 404 or "not found" in detail_lower:
            return {
                "status": "already_reversed",
                "erp": "netsuite",
                "reference_id": erp_reference,
                "reversal_method": "delete",
                "reversal_ref": erp_reference,
                "reason": "bill_not_found_in_erp",
            }
        elif code_upper == "INVALID_KEY_OR_REF":
            reason_code = "erp_invalid_reference"

        logger.error(
            "NetSuite Vendor Bill reverse HTTP error: status=%d reason=%s code=%s detail=%s",
            status_code, reason_code, erp_error_code, erp_error_detail[:200],
        )
        return {
            "status": "error",
            "erp": "netsuite",
            "reference_id": erp_reference,
            "reversal_method": "delete",
            "reason": reason_code,
            "erp_error_detail": erp_error_detail,
            "erp_error_code": erp_error_code,
            "needs_reauth": status_code == 401,
        }
    except Exception as exc:
        logger.error(
            "NetSuite Vendor Bill reverse error: %s: %s",
            type(exc).__name__, exc,
        )
        return {
            "status": "error",
            "erp": "netsuite",
            "reference_id": erp_reference,
            "reversal_method": "delete",
            "reason": "bill_reversal_failed",
            "erp_error_detail": type(exc).__name__,
        }


# ==================== Bill & Credit Note Lookup ====================

async def get_vendor_bill_netsuite(
    connection,
    bill_id: str,
) -> Dict[str, Any]:
    """Fetch a vendor bill record from NetSuite to resolve settlement context."""
    if not connection.account_id:
        return {"status": "error", "erp": "netsuite", "reason": "NetSuite account ID not configured"}
    bill_ref = str(bill_id or "").strip()
    if not bill_ref:
        return {"status": "error", "erp": "netsuite", "reason": "missing_bill_id"}

    url = f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/record/v1/vendorBill/{bill_ref}"
    auth_header = _oauth_header(connection, "GET", url)
    try:
        client = get_http_client()
        response = await client.get(
            url,
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
            },
            timeout=60,
        )
        if response.status_code == 401:
            return {"status": "error", "erp": "netsuite", "reason": "Authentication failed", "needs_reauth": True}

        response.raise_for_status()
        payload = response.json()
        entity = payload.get("entity") if isinstance(payload.get("entity"), dict) else {}
        return {
            "status": "success",
            "erp": "netsuite",
            "bill_id": str(payload.get("id") or bill_ref),
            "vendor_id": str(entity.get("id") or "").strip() or None,
            "tran_id": payload.get("tranId"),
            "currency": (
                str((payload.get("currency") or {}).get("id") or "").strip()
                if isinstance(payload.get("currency"), dict)
                else None
            ),
        }
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("NetSuite vendor bill GET HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            payload = e.response.json()
        except Exception:
            payload = None
        validation_message = _extract_netsuite_validation_message(payload)
        if validation_message:
            reason = validation_message
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("NetSuite vendor bill GET error: %s", type(e).__name__)
        return {"status": "error", "erp": "netsuite", "reason": "bill_lookup_failed"}


async def find_credit_note_netsuite(
    connection,
    credit_note_number: str,
) -> Optional[Dict[str, Any]]:
    """Find a vendor credit in NetSuite by transaction number."""
    if not connection.account_id:
        return None
    safe_number = _sanitize_netsuite_like_operand(credit_note_number)
    if not safe_number:
        return None
    literal = _escape_query_literal(safe_number)
    query = (
        f"SELECT id, tranid, amountremaining, entity FROM transaction "
        f"WHERE tranid = '{literal}' AND type = 'VendCred' "
        f"FETCH FIRST 1 ROWS ONLY"
    )
    url = f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/query/v1/suiteql"
    auth_header = _oauth_header(connection, "POST", url)
    try:
        client = get_http_client()
        response = await client.post(
            url,
            json={"q": query},
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
                "Prefer": "transient",
            },
            timeout=60,
        )
        response.raise_for_status()
        items = response.json().get("items", [])
        if items:
            row = items[0]
            return {
                "credit_note_id": str(row.get("id")),
                "credit_note_number": row.get("tranid"),
                "amount_remaining": row.get("amountremaining"),
                "vendor_id": (
                    str(row.get("entity"))
                    if row.get("entity") is not None
                    else None
                ),
                "erp": "netsuite",
            }
    except Exception as e:
        logger.error("NetSuite credit note lookup error: %s", e)
    return None


# ==================== Credit Application ====================

async def apply_credit_note_to_netsuite(
    connection,
    application,
    *,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """Apply a NetSuite vendor credit to an existing vendor bill."""
    if not connection.account_id:
        return {"status": "error", "erp": "netsuite", "reason": "NetSuite account ID not configured"}

    missing_fields = []
    if not str(application.target_erp_reference or "").strip():
        missing_fields.append("target_erp_reference")
    if not str(application.credit_note_number or "").strip():
        missing_fields.append("credit_note_number")
    if float(application.amount or 0.0) <= 0:
        missing_fields.append("amount")
    if missing_fields:
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": "netsuite_credit_application_validation_failed",
            "missing_fields": missing_fields,
        }

    credit_note = await find_credit_note_netsuite(connection, str(application.credit_note_number or ""))
    if not credit_note or not credit_note.get("credit_note_id"):
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": "credit_note_not_found",
            "credit_note_number": application.credit_note_number,
        }

    remaining_credit = credit_note.get("amount_remaining")
    try:
        if remaining_credit is not None and round(float(application.amount or 0.0), 2) > round(float(remaining_credit), 2):
            return {
                "status": "error",
                "erp": "netsuite",
                "reason": "credit_amount_exceeds_remaining_credit",
                "credit_note_number": application.credit_note_number,
                "remaining_credit": round(float(remaining_credit), 2),
            }
    except (TypeError, ValueError):
        pass

    credit_id = str(credit_note["credit_note_id"]).strip()
    target_ref = str(application.target_erp_reference or "").strip()
    url = f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/record/v1/vendorCredit/{credit_id}"
    auth_header = _oauth_header(connection, "PATCH", url)
    payload = {
        "apply": {
            "items": [
                {
                    "doc": {"id": target_ref},
                    "apply": True,
                    "amount": round(float(application.amount or 0.0), 2),
                }
            ]
        }
    }

    try:
        client = get_http_client()
        response = await client.patch(
            url,
            json=payload,
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
                "Prefer": "respond-async",
            },
            timeout=60,
        )
        if response.status_code == 401:
            return {"status": "error", "erp": "netsuite", "reason": "Authentication failed", "needs_reauth": True}

        response.raise_for_status()
        if response.status_code == 202:
            location = response.headers.get("Location", "").strip()
            if location:
                poll_result = await _poll_netsuite_async_result(
                    client,
                    auth_header=auth_header,
                    location=location,
                )
                if poll_result is None:
                    return {"status": "error", "erp": "netsuite", "reason": "async_timeout"}
        return {
            "status": "success",
            "erp": "netsuite",
            "erp_reference": f"{credit_id}:{target_ref}",
            "credit_note_reference": credit_id,
            "credit_note_number": credit_note.get("credit_note_number"),
            "target_erp_reference": target_ref,
            "amount": round(float(application.amount or 0.0), 2),
            "idempotency_key": idempotency_key,
        }
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("NetSuite credit application HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            response_payload = e.response.json()
        except Exception:
            response_payload = None
        validation_message = _extract_netsuite_validation_message(response_payload)
        if validation_message:
            reason = validation_message
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("NetSuite credit application error: %s", type(e).__name__)
        return {"status": "error", "erp": "netsuite", "reason": "credit_application_failed"}


# ==================== Settlement ====================

async def apply_settlement_to_netsuite(
    connection,
    application,
    *,
    gl_map: Optional[Dict[str, str]] = None,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """Create a NetSuite vendor payment against a posted vendor bill."""
    from solden.integrations.erp_router import get_account_code

    if not connection.account_id:
        return {"status": "error", "erp": "netsuite", "reason": "NetSuite account ID not configured"}

    source_document_type = str(application.source_document_type or "").strip().lower()
    if source_document_type == "refund":
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": "refund_settlement_api_not_available_for_connector",
        }

    missing_fields = []
    if not str(application.target_erp_reference or "").strip():
        missing_fields.append("target_erp_reference")
    if float(application.amount or 0.0) <= 0:
        missing_fields.append("amount")
    if missing_fields:
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": "netsuite_settlement_validation_failed",
            "missing_fields": missing_fields,
        }

    bill = await get_vendor_bill_netsuite(connection, str(application.target_erp_reference or ""))
    if bill.get("status") != "success":
        return bill
    if not bill.get("vendor_id"):
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": "bill_vendor_not_resolved",
            "target_erp_reference": application.target_erp_reference,
        }

    url = f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/record/v1/vendorPayment"
    auth_header = _oauth_header(connection, "POST", url)
    payload = {
        "entity": {"id": bill["vendor_id"]},
        "account": {"id": get_account_code("netsuite", "cash", gl_map)},
        "tranDate": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "memo": (
            str(application.note or application.source_reference or f"Settlement for {bill.get('tran_id') or application.target_erp_reference}")
            [:300]
        ),
        "apply": {
            "items": [
                {
                    "doc": {"id": str(application.target_erp_reference).strip()},
                    "apply": True,
                    "amount": round(float(application.amount or 0.0), 2),
                }
            ]
        },
    }

    try:
        client = get_http_client()
        response = await client.post(
            url,
            json=payload,
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
                "Prefer": "respond-async",
            },
            timeout=60,
        )
        if response.status_code == 401:
            return {"status": "error", "erp": "netsuite", "reason": "Authentication failed", "needs_reauth": True}

        response.raise_for_status()

        if response.status_code == 202:
            location = response.headers.get("Location", "").strip()
            if location:
                poll_result = await _poll_netsuite_async_result(
                    client,
                    auth_header=auth_header,
                    location=location,
                )
                if poll_result is None:
                    return {"status": "error", "erp": "netsuite", "reason": "async_timeout"}
                payment_id = poll_result.get("id") or poll_result.get("internalId")
                return {
                    "status": "success",
                    "erp": "netsuite",
                    "erp_reference": payment_id,
                    "payment_id": payment_id,
                    "target_erp_reference": str(application.target_erp_reference).strip(),
                    "amount": round(float(application.amount or 0.0), 2),
                    "source_reference": application.source_reference,
                    "idempotency_key": idempotency_key,
                }
            return {"status": "error", "erp": "netsuite", "reason": "async_timeout"}

        result = response.json()
        payment_id = result.get("id") or result.get("internalId")
        return {
            "status": "success",
            "erp": "netsuite",
            "erp_reference": payment_id,
            "payment_id": payment_id,
            "target_erp_reference": str(application.target_erp_reference).strip(),
            "amount": round(float(application.amount or 0.0), 2),
            "source_reference": application.source_reference,
            "idempotency_key": idempotency_key,
        }
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("NetSuite settlement payment HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            response_payload = e.response.json()
        except Exception:
            response_payload = None
        validation_message = _extract_netsuite_validation_message(response_payload)
        if validation_message:
            reason = validation_message
        return {
            "status": "error",
            "erp": "netsuite",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("NetSuite settlement payment error: %s", type(e).__name__)
        return {"status": "error", "erp": "netsuite", "reason": "settlement_application_failed"}


# ==================== Vendor Management ====================

async def create_vendor_netsuite(
    connection,
    vendor,
) -> Dict[str, Any]:
    """Create vendor in NetSuite."""
    if not connection.account_id:
        return {"status": "error", "erp": "netsuite", "reason": "NetSuite not configured"}

    ns_vendor = {
        "companyName": vendor.name,
        "entityId": vendor.name.replace(" ", "_")[:32],  # External ID
        "email": vendor.email,
        "phone": vendor.phone,
    }

    if vendor.currency:
        ns_vendor["currency"] = {"refName": vendor.currency}

    url = f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/record/v1/vendor"
    auth_header = _oauth_header(connection, "POST", url)

    try:
        client = get_http_client()
        response = await client.post(
            url,
            json=ns_vendor,
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
            },
            timeout=60,
        )
        response.raise_for_status()
        result = response.json()

        return {
            "status": "success",
            "vendor_id": result.get("id"),
            "entity_id": result.get("entityId"),
        }
    except Exception as e:
        logger.error("NetSuite vendor creation error: %s", type(e).__name__)
        return {"status": "error", "erp": "netsuite", "reason": "vendor_creation_failed"}


async def find_vendor_netsuite(
    connection,
    name: Optional[str] = None,
    email: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Find vendor in NetSuite."""
    if not connection.account_id:
        return None

    # Build SuiteQL query with strict sanitization through shared helper.
    name_operand = _sanitize_netsuite_like_operand(name)
    email_operand = _sanitize_netsuite_email_operand(email)
    query = _build_netsuite_vendor_lookup_query(
        name_operand=name_operand,
        email_operand=email_operand,
    )
    if not query:
        return None

    url = f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/query/v1/suiteql"
    auth_header = _oauth_header(connection, "POST", url)

    try:
        client = get_http_client()
        response = await client.post(
            url,
            json={"q": query},
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
                "Prefer": "transient",
            },
            timeout=60,
        )
        response.raise_for_status()
        result = response.json()

        items = result.get("items", [])
        if items:
            v = items[0]
            return {
                "vendor_id": str(v.get("id")),
                "name": v.get("companyname"),
                "email": v.get("email"),
            }
    except Exception as e:
        logger.error(f"NetSuite vendor search error: {e}")

    return None


# ==================== Bill Finder ====================

async def find_bill_netsuite(
    connection,
    invoice_number: str,
) -> Optional[Dict[str, Any]]:
    """Check if a vendor bill already exists in NetSuite."""
    if not connection.account_id:
        return None
    safe_number = _sanitize_netsuite_like_operand(invoice_number)
    if not safe_number:
        return None
    literal = _escape_query_literal(safe_number)
    query = (
        f"SELECT id, tranid, amount FROM transaction "
        f"WHERE tranid = '{literal}' AND type = 'VendBill' "
        f"FETCH FIRST 1 ROWS ONLY"
    )
    url = f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/query/v1/suiteql"
    auth_header = _oauth_header(connection, "POST", url)
    try:
        client = get_http_client()
        response = await client.post(
            url,
            json={"q": query},
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
                "Prefer": "transient",
            },
            timeout=60,
        )
        response.raise_for_status()
        items = response.json().get("items", [])
        if items:
            row = items[0]
            return {
                "bill_id": str(row.get("id")),
                "doc_number": row.get("tranid"),
                "amount": row.get("amount"),
                "erp": "netsuite",
            }
    except Exception as e:
        logger.error("NetSuite bill lookup error: %s", e)
    return None


# ==================== Attachment ====================

async def _attach_to_netsuite(
    connection, bill_id: str, file_bytes: bytes, filename: str,
) -> Optional[Dict[str, Any]]:
    """Upload an attachment to a NetSuite VendorBill.

    Reads the NetSuite account_id from the connection (not from a
    ``credentials`` attribute — ``ERPConnection`` is flat). Builds the
    OAuth Authorization header and composes the full header dict for
    the POST; previous version passed wrong arg order to
    ``_oauth_header`` and treated the returned string as a dict.
    """
    import base64

    account_id = getattr(connection, "account_id", None) or ""
    if not account_id:
        return None
    encoded = base64.b64encode(file_bytes).decode()
    base_url = f"https://{account_id}.suitetalk.api.netsuite.com"
    url = f"{base_url}/services/rest/record/v1/vendorbill/{bill_id}/file"
    # _oauth_header returns the Authorization string; the full header
    # dict is composed here.
    auth_header = _oauth_header(connection, "POST", url)
    headers = {
        "Authorization": auth_header,
        "Content-Type": "application/json",
    }
    payload = {"name": filename, "content": encoded}
    client = get_http_client()
    resp = await client.post(url, headers=headers, json=payload, timeout=30)
    resp.raise_for_status()
    return {"attached": True, "erp": "netsuite", "filename": filename}


# ==================== Payment Status Lookup ====================

async def get_payment_status_netsuite(
    connection,
    bill_id: str,
) -> Dict[str, Any]:
    """Read payment status for a NetSuite vendor bill. GET only — never executes payments.

    Uses SuiteQL to check status and amountremaining for the vendor bill.
    """
    if not connection.account_id:
        return {"paid": False, "error": "NetSuite account ID not configured"}

    safe_id = _sanitize_netsuite_like_operand(bill_id)
    if not safe_id:
        return {"paid": False, "error": "invalid_bill_reference"}
    literal = _escape_query_literal(safe_id)
    query = (
        f"SELECT id, tranid, status, amount, amountremaining, amountpaid "
        f"FROM transaction "
        f"WHERE id = '{literal}' AND type = 'VendBill' "
        f"FETCH FIRST 1 ROWS ONLY"
    )
    url = f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest/query/v1/suiteql"
    auth_header = _oauth_header(connection, "POST", url)
    try:
        client = get_http_client()
        response = await client.post(
            url,
            json={"q": query},
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
                "Prefer": "transient",
            },
            timeout=60,
        )
        if response.status_code == 401:
            return {"paid": False, "error": "authentication_failed", "needs_reauth": True}

        response.raise_for_status()
        items = response.json().get("items", [])
        if not items:
            return {"paid": False, "reason": "not_found"}

        row = items[0]
        total = float(row.get("amount") or 0)
        remaining = float(row.get("amountremaining") or 0)
        paid = float(row.get("amountpaid") or 0)
        status_val = str(row.get("status") or "").strip()

        # Detect payment processing failures
        if status_val.lower() in ("pendapprov", "pendingapproval"):
            return {
                "paid": False,
                "payment_failed": True,
                "reason": "payment_pending_approval",
            }

        if remaining <= 0 and total > 0:
            # Determine closure method: if fully closed but no payment
            # recorded, may be a credit memo application
            closure_method = "payment"
            if paid <= 0 and remaining <= 0:
                closure_method = "credit_applied"
            elif paid > 0 and paid < total and remaining <= 0:
                # Part payment, part credit
                closure_method = "payment"

            result = {
                "paid": True,
                "payment_amount": round(paid or total, 2),
                "payment_date": "",
                "payment_method": "",
                "payment_reference": str(row.get("id") or ""),
                "partial": False,
                "remaining_balance": 0.0,
            }
            if closure_method != "payment":
                result["closure_method"] = closure_method
            return result
        elif paid > 0 and remaining > 0:
            return {
                "paid": False,
                "payment_amount": round(paid, 2),
                "payment_date": "",
                "payment_method": "",
                "payment_reference": str(row.get("id") or ""),
                "partial": True,
                "remaining_balance": round(remaining, 2),
            }
        else:
            return {"paid": False, "reason": "unpaid"}
    except httpx.HTTPStatusError as e:
        logger.error("NetSuite payment status HTTP error: status=%d", e.response.status_code)
        return {"paid": False, "error": f"http_{e.response.status_code}"}
    except Exception as e:
        logger.error("NetSuite payment status error: %s", type(e).__name__)
        return {"paid": False, "error": "payment_status_lookup_failed"}


# ==================== Chart of Accounts (Normalized) ====================

_NS_ACCOUNT_TYPE_MAP = {
    "acctrec": "asset",
    "acctpay": "liability",
    "bank": "asset",
    "cogs": "expense",
    "credcard": "liability",
    "deferexpense": "asset",
    "deferrevenue": "liability",
    "equity": "equity",
    "expense": "expense",
    "fixedasset": "asset",
    "income": "revenue",
    "longtermliab": "liability",
    "nonposting": "other",
    "othcurasset": "asset",
    "othcurliab": "liability",
    "othexpense": "expense",
    "othincome": "revenue",
    "statistical": "other",
    "unbilledrec": "asset",
}


async def get_chart_of_accounts_netsuite(connection) -> List[Dict[str, Any]]:
    """Fetch all accounts from NetSuite via SuiteQL.

    Returns a normalized list of account dicts.  Returns ``[]`` on any error
    so the caller is never blocked.
    """
    if not connection.account_id:
        return []

    suiteql_url = (
        f"https://{connection.account_id}.suitetalk.api.netsuite.com"
        "/services/rest/query/v1/suiteql"
    )
    auth_header = _oauth_header(connection, "POST", suiteql_url)

    query = "SELECT id, acctnumber, acctname, accttype, isinactive, currency FROM account"
    try:
        client = get_http_client()
        response = await client.post(
            suiteql_url,
            json={"q": query},
            headers={
                "Authorization": auth_header,
                "Content-Type": "application/json",
                "Prefer": "transient",
            },
            params={"limit": 1000},
            timeout=60,
        )
        response.raise_for_status()
        result = response.json()

        accounts: List[Dict[str, Any]] = []
        for item in result.get("items", []):
            raw_type = str(item.get("accttype") or "").strip().lower()
            is_inactive = item.get("isinactive")
            active = True
            if isinstance(is_inactive, str):
                active = is_inactive.strip().upper() not in {"T", "TRUE", "YES", "1"}
            elif isinstance(is_inactive, bool):
                active = not is_inactive

            currency_val = item.get("currency")
            currency = ""
            if isinstance(currency_val, dict):
                currency = str(currency_val.get("refName") or currency_val.get("name") or "")
            elif currency_val:
                currency = str(currency_val)

            accounts.append({
                "id": str(item.get("id") or ""),
                "code": str(item.get("acctnumber") or ""),
                "name": str(item.get("acctname") or ""),
                "type": _NS_ACCOUNT_TYPE_MAP.get(raw_type, raw_type),
                "sub_type": raw_type,
                "active": active,
                "currency": currency,
            })
        return accounts

    except Exception as e:
        logger.error("Failed to fetch NetSuite chart of accounts: %s", type(e).__name__)
        return []


# ==================== Preflight ====================


async def preflight_netsuite(connection) -> Dict[str, Any]:
    """Validate a NetSuite connection beyond "auth works".

    The bare ``get_netsuite_accounts()`` connection test accepts any
    tokens that NetSuite accepts — even if the Integration Record
    lacks the scopes needed to actually post vendor bills. The first
    invoice then fails with a 403 weeks after the customer thought
    they were set up.

    This preflight actively exercises the three code paths the AP
    pipeline depends on (read vendors, read vendor bills, read chart
    of accounts) and reports per-check status + the rough shape of
    the customer's chart (how many accounts, how many expense
    accounts, how many liability accounts). Callers should surface
    the per-check result so the customer can see exactly which
    permission is missing before onboarding advances.

    Returns::

        {
            "ok": bool,               # all critical checks passed
            "checks": {
                "vendors_readable": {...},
                "vendor_bills_readable": {...},
                "chart_of_accounts_readable": {...},
            },
            "chart_summary": {
                "total": int,
                "expense_accounts": int,
                "liability_accounts": int,
                "bank_accounts": int,
            },
            "warnings": [str, ...],
        }
    """
    checks: Dict[str, Dict[str, Any]] = {}
    warnings: List[str] = []

    if not connection.account_id:
        return {
            "ok": False,
            "checks": {},
            "chart_summary": {},
            "warnings": ["account_id missing"],
        }

    base_url = f"https://{connection.account_id}.suitetalk.api.netsuite.com/services/rest"
    client = get_http_client()

    async def _probe(label: str, url: str) -> Dict[str, Any]:
        """GET the URL, treat HTTP status as the check outcome."""
        try:
            auth_header = _oauth_header(connection, "GET", url)
            response = await client.get(
                url,
                headers={"Authorization": auth_header, "Prefer": "transient"},
                params={"limit": 1},
                timeout=30,
            )
            status = response.status_code
            if status == 200:
                return {"ok": True, "status": status, "detail": "readable"}
            if status in (401, 403):
                return {
                    "ok": False,
                    "status": status,
                    "detail": (
                        "forbidden — the Integration Record token does not "
                        f"have permission to read {label}. Check the role's "
                        "permissions in NetSuite."
                    ),
                }
            return {
                "ok": False,
                "status": status,
                "detail": f"unexpected status {status}",
            }
        except Exception as exc:
            return {"ok": False, "status": None, "detail": f"network error: {exc}"}

    checks["vendors_readable"] = await _probe(
        "vendors", f"{base_url}/record/v1/vendor"
    )
    checks["vendor_bills_readable"] = await _probe(
        "vendor bills", f"{base_url}/record/v1/vendorBill"
    )

    # Chart of accounts via the existing helper — gives us counts
    # per account type which the UI uses to confirm the customer's
    # chart is sane (at least one expense account exists).
    accounts = await get_chart_of_accounts_netsuite(connection)
    chart_summary = {
        "total": len(accounts),
        "expense_accounts": sum(1 for a in accounts if str(a.get("type", "")).lower() == "expense"),
        "liability_accounts": sum(1 for a in accounts if str(a.get("type", "")).lower() == "liability"),
        "bank_accounts": sum(1 for a in accounts if str(a.get("type", "")).lower() in {"bank", "asset"}),
    }
    checks["chart_of_accounts_readable"] = {
        "ok": chart_summary["total"] > 0,
        "status": 200 if chart_summary["total"] > 0 else None,
        "detail": (
            f"{chart_summary['total']} accounts readable"
            if chart_summary["total"] > 0
            else "no accounts returned — check SuiteQL / Lists permission"
        ),
    }

    if chart_summary["total"] > 0 and chart_summary["expense_accounts"] == 0:
        warnings.append(
            "chart has no expense accounts — AP bills need at least one expense "
            "account to debit against"
        )
    if chart_summary["total"] > 0 and chart_summary["liability_accounts"] == 0:
        warnings.append(
            "chart has no liability accounts — the AP account bills credit against "
            "may be missing"
        )

    critical_ok = all(c["ok"] for c in checks.values())

    return {
        "ok": critical_ok and not warnings,
        "critical_ok": critical_ok,
        "checks": checks,
        "chart_summary": chart_summary,
        "warnings": warnings,
    }


# ==================== Vendor List ====================


async def list_all_vendors_netsuite(connection) -> List[Dict[str, Any]]:
    """Fetch all vendors from NetSuite via SuiteQL with pagination.

    SuiteQL uses ``offset`` + ``limit`` query params.
    Returns a normalized list of vendor dicts.  Returns ``[]`` on any error.
    """
    if not connection.account_id:
        return []

    suiteql_url = (
        f"https://{connection.account_id}.suitetalk.api.netsuite.com"
        "/services/rest/query/v1/suiteql"
    )

    query = (
        "SELECT id, companyName, email, phone, "
        "defaultAddress, terms, isInactive, currency "
        "FROM vendor"
    )
    page_size = 1000
    offset = 0
    all_vendors: List[Dict[str, Any]] = []

    try:
        client = get_http_client()
        while True:
            auth_header = _oauth_header(connection, "POST", suiteql_url)
            response = await client.post(
                suiteql_url,
                json={"q": query},
                headers={
                    "Authorization": auth_header,
                    "Content-Type": "application/json",
                    "Prefer": "transient",
                },
                params={"limit": page_size, "offset": offset},
                timeout=60,
            )

            if response.status_code == 401:
                logger.warning("NetSuite token expired during vendor list fetch")
                break

            response.raise_for_status()
            result = response.json()

            items = result.get("items", [])
            if not items:
                break

            for v in items:
                is_inactive = v.get("isinactive") or v.get("isInactive")
                active = True
                if isinstance(is_inactive, str):
                    active = is_inactive.strip().upper() not in {"T", "TRUE", "YES", "1"}
                elif isinstance(is_inactive, bool):
                    active = not is_inactive

                currency_val = v.get("currency")
                currency = ""
                if isinstance(currency_val, dict):
                    currency = str(currency_val.get("refName") or currency_val.get("name") or "")
                elif currency_val:
                    currency = str(currency_val)

                terms_val = v.get("terms")
                terms = ""
                if isinstance(terms_val, dict):
                    terms = str(terms_val.get("refName") or terms_val.get("name") or "")
                elif terms_val:
                    terms = str(terms_val)

                all_vendors.append({
                    "vendor_id": str(v.get("id") or ""),
                    "name": str(v.get("companyname") or v.get("companyName") or ""),
                    "email": str(v.get("email") or ""),
                    "phone": str(v.get("phone") or ""),
                    "tax_id": "",
                    "currency": currency,
                    "active": active,
                    "address": str(v.get("defaultaddress") or v.get("defaultAddress") or ""),
                    "payment_terms": terms,
                    "balance": 0.0,
                })

            if len(items) < page_size:
                break
            offset += page_size

        return all_vendors

    except Exception as e:
        logger.error("Failed to fetch NetSuite vendor list: %s", type(e).__name__)
        return all_vendors or []


async def get_dimension_masters_netsuite(connection) -> List[Dict[str, Any]]:
    """Fetch dimension masters (departments / classes / locations) WITH parent
    refs via SuiteQL, for the dimension graph (H5 deepening).

    Returns normalized rows ``{kind, external_id, code, name,
    parent_external_id, active}``; ``[]`` on any error so the caller is never
    blocked. Request shape mirrors get_chart_of_accounts_netsuite; NEEDS
    live-sandbox validation (same posture as the PO write adapters).
    """
    if not connection.account_id:
        return []
    suiteql_url = (
        f"https://{connection.account_id}.suitetalk.api.netsuite.com"
        "/services/rest/query/v1/suiteql"
    )
    kinds = (
        ("department", "SELECT id, name, parent, isinactive FROM department"),
        ("classification", "SELECT id, name, parent, isinactive FROM classification"),
        ("location", "SELECT id, name, parent, isinactive FROM location"),
    )
    out: List[Dict[str, Any]] = []
    try:
        client = get_http_client()
        for kind, query in kinds:
            auth_header = _oauth_header(connection, "POST", suiteql_url)
            response = await client.post(
                suiteql_url,
                json={"q": query},
                headers={
                    "Authorization": auth_header,
                    "Content-Type": "application/json",
                    "Prefer": "transient",
                },
                params={"limit": 1000},
                timeout=60,
            )
            response.raise_for_status()
            for item in response.json().get("items", []):
                inactive = item.get("isinactive")
                active = str(inactive).strip().upper() not in {"T", "TRUE", "YES", "1"}
                name = str(item.get("name") or "").strip()
                if not name:
                    continue
                out.append({
                    "kind": kind,
                    "external_id": str(item.get("id") or ""),
                    "code": name,
                    "name": name,
                    "parent_external_id": str(item.get("parent") or "") or None,
                    "active": active,
                })
        return out
    except Exception as e:  # noqa: BLE001
        logger.error("Failed to fetch NetSuite dimension masters: %s", type(e).__name__)
        return []
